# Basketball Reference API

In [1]:
import pandas as pd
from datetime import datetime, timedelta
import time

In [2]:
from basketball_reference_web_scraper import client
from basketball_reference_web_scraper.data import League, Location, Outcome, OutputType
from basketball_reference_web_scraper.data import OutputWriteOption, Position, PeriodType, Team

## Team Box Scores

In [ ]:
start_time = time.time()

# initialize empty list
team_bs = []

# define start and end dates
start_date = datetime(2010, 1, 1)
end_date = datetime(2014, 12, 31) 

# loop over each day in the range
current_date = start_date
while current_date <= end_date:
    
    print(current_date)
    
    # fetch data for current day
    day_data = client.team_box_scores(day=current_date.day, 
                                      month=current_date.month, 
                                      year=current_date.year)
    
    # check if day_data is not empty
    if day_data:
        # add current date to each dictionary in day_data
        for record in day_data:
            record['date'] = current_date

        # append the day's data (list of dictionaries) to team_box_scores
        team_bs.extend(day_data)

    # add time delay between requests
    time.sleep(30)
    
    # move to next day
    current_date += timedelta(days=1)

# convert list of dictionaries to a DataFrame
team_bs_df = pd.DataFrame(team_bs)

end_time = time.time()
total_time = end_time - start_time
print(f"Total time taken: {total_time} seconds")

2010-01-01 00:00:00
2010-01-02 00:00:00
2010-01-03 00:00:00
2010-01-04 00:00:00
2010-01-05 00:00:00
2010-01-06 00:00:00
2010-01-07 00:00:00
2010-01-08 00:00:00
2010-01-09 00:00:00
2010-01-10 00:00:00
2010-01-11 00:00:00
2010-01-12 00:00:00
2010-01-13 00:00:00
2010-01-14 00:00:00
2010-01-15 00:00:00
2010-01-16 00:00:00
2010-01-17 00:00:00
2010-01-18 00:00:00
2010-01-19 00:00:00
2010-01-20 00:00:00
2010-01-21 00:00:00
2010-01-22 00:00:00
2010-01-23 00:00:00
2010-01-24 00:00:00
2010-01-25 00:00:00
2010-01-26 00:00:00
2010-01-27 00:00:00
2010-01-28 00:00:00
2010-01-29 00:00:00
2010-01-30 00:00:00
2010-01-31 00:00:00
2010-02-01 00:00:00
2010-02-02 00:00:00
2010-02-03 00:00:00
2010-02-04 00:00:00
2010-02-05 00:00:00
2010-02-06 00:00:00
2010-02-07 00:00:00
2010-02-08 00:00:00
2010-02-09 00:00:00
2010-02-10 00:00:00
2010-02-11 00:00:00
2010-02-12 00:00:00
2010-02-13 00:00:00
2010-02-14 00:00:00
2010-02-15 00:00:00
2010-02-16 00:00:00
2010-02-17 00:00:00
2010-02-18 00:00:00
2010-02-19 00:00:00
2010-02-20 00:00:00
2010-02-21 00:00:00
2010-02-22 00:00:00
2010-02-23 00:00:00
2010-02-24 00:00:00
2010-02-25 00:00:00
2010-02-26 00:00:00
2010-02-27 00:00:00
2010-02-28 00:00:00
2010-03-01 00:00:00
2010-03-02 00:00:00
2010-03-03 00:00:00
2010-03-04 00:00:00
2010-03-05 00:00:00
2010-03-06 00:00:00
2010-03-07 00:00:00
2010-03-08 00:00:00
2010-03-09 00:00:00
2010-03-10 00:00:00
2010-03-11 00:00:00
2010-03-12 00:00:00
2010-03-13 00:00:00
2010-03-14 00:00:00
2010-03-15 00:00:00
2010-03-16 00:00:00
2010-03-17 00:00:00
2010-03-18 00:00:00
2010-03-19 00:00:00
2010-03-20 00:00:00
2010-03-21 00:00:00
2010-03-22 00:00:00
2010-03-23 00:00:00
2010-03-24 00:00:00
2010-03-25 00:00:00
2010-03-26 00:00:00
2010-03-27 00:00:00
2010-03-28 00:00:00
2010-03-29 00:00:00
2010-03-30 00:00:00
2010-03-31 00:00:00
2010-04-01 00:00:00
2010-04-02 00:00:00
2010-04-03 00:00:00
2010-04-04 00:00:00
2010-04-05 00:00:00
2010-04-06 00:00:00
2010-04-07 00:00:00
2010-04-08 00:00:00
2010-04-09 00:00:00
2010-04-10 00:00:00
2010-04-11 00:00:00
2010-04-12 00:00:00
2010-04-13 00:00:00
2010-04-14 00:00:00
2010-04-15 00:00:00
2010-04-16 00:00:00
2010-04-17 00:00:00
2010-04-18 00:00:00
2010-04-19 00:00:00
2010-04-20 00:00:00
2010-04-21 00:00:00
2010-04-22 00:00:00
2010-04-23 00:00:00
2010-04-24 00:00:00
2010-04-25 00:00:00
2010-04-26 00:00:00
2010-04-27 00:00:00
2010-04-28 00:00:00
2010-04-29 00:00:00
2010-04-30 00:00:00
2010-05-01 00:00:00
2010-05-02 00:00:00
2010-05-03 00:00:00
2010-05-04 00:00:00
2010-05-05 00:00:00
2010-05-06 00:00:00
2010-05-07 00:00:00
2010-05-08 00:00:00
2010-05-09 00:00:00
2010-05-10 00:00:00
2010-05-11 00:00:00
2010-05-12 00:00:00
2010-05-13 00:00:00
2010-05-14 00:00:00
2010-05-15 00:00:00
2010-05-16 00:00:00
2010-05-17 00:00:00
2010-05-18 00:00:00
2010-05-19 00:00:00
2010-05-20 00:00:00
2010-05-21 00:00:00
2010-05-22 00:00:00
2010-05-23 00:00:00
2010-05-24 00:00:00
2010-05-25 00:00:00
2010-05-26 00:00:00
2010-05-27 00:00:00
2010-05-28 00:00:00
2010-05-29 00:00:00
2010-05-30 00:00:00
2010-05-31 00:00:00
2010-06-01 00:00:00
2010-06-02 00:00:00
2010-06-03 00:00:00
2010-06-04 00:00:00
2010-06-05 00:00:00
2010-06-06 00:00:00
2010-06-07 00:00:00
2010-06-08 00:00:00
2010-06-09 00:00:00
2010-06-10 00:00:00
2010-06-11 00:00:00
2010-06-12 00:00:00
2010-06-13 00:00:00
2010-06-14 00:00:00
2010-06-15 00:00:00
2010-06-16 00:00:00
2010-06-17 00:00:00
2010-06-18 00:00:00
2010-06-19 00:00:00
2010-06-20 00:00:00
2010-06-21 00:00:00
2010-06-22 00:00:00
2010-06-23 00:00:00
2010-06-24 00:00:00
2010-06-25 00:00:00
2010-06-26 00:00:00
2010-06-27 00:00:00
2010-06-28 00:00:00
2010-06-29 00:00:00
2010-06-30 00:00:00
2010-07-01 00:00:00
2010-07-02 00:00:00
2010-07-03 00:00:00
2010-07-04 00:00:00
2010-07-05 00:00:00
2010-07-06 00:00:00
2010-07-07 00:00:00
2010-07-08 00:00:00
2010-07-09 00:00:00
2010-07-10 00:00:00
2010-07-11 00:00:00
2010-07-12 00:00:00
2010-07-13 00:00:00
2010-07-14 00:00:00
2010-07-15 00:00:00
2010-07-16 00:00:00
2010-07-17 00:00:00
2010-07-18 00:00:00
2010-07-19 00:00:00
2010-07-20 00:00:00
2010-07-21 00:00:00
2010-07-22 00:00:00
2010-07-23 00:00:00
2010-07-24 00:00:00
2010-07-25 00:00:00
2010-07-26 00:00:00
2010-07-27 00:00:00
2010-07-28 00:00:00
2010-07-29 00:00:00
2010-07-30 00:00:00
2010-07-31 00:00:00
2010-08-01 00:00:00
2010-08-02 00:00:00
2010-08-03 00:00:00
2010-08-04 00:00:00
2010-08-05 00:00:00
2010-08-06 00:00:00
2010-08-07 00:00:00
2010-08-08 00:00:00
2010-08-09 00:00:00
2010-08-10 00:00:00
2010-08-11 00:00:00
2010-08-12 00:00:00
2010-08-13 00:00:00
2010-08-14 00:00:00
2010-08-15 00:00:00
2010-08-16 00:00:00
2010-08-17 00:00:00
2010-08-18 00:00:00
2010-08-19 00:00:00
2010-08-20 00:00:00
2010-08-21 00:00:00
2010-08-22 00:00:00
2010-08-23 00:00:00
2010-08-24 00:00:00
2010-08-25 00:00:00
2010-08-26 00:00:00
2010-08-27 00:00:00
2010-08-28 00:00:00
2010-08-29 00:00:00
2010-08-30 00:00:00
2010-08-31 00:00:00
2010-09-01 00:00:00
2010-09-02 00:00:00
2010-09-03 00:00:00
2010-09-04 00:00:00
2010-09-05 00:00:00
2010-09-06 00:00:00
2010-09-07 00:00:00
2010-09-08 00:00:00
2010-09-09 00:00:00
2010-09-10 00:00:00
2010-09-11 00:00:00
2010-09-12 00:00:00
2010-09-13 00:00:00
2010-09-14 00:00:00
2010-09-15 00:00:00
2010-09-16 00:00:00
2010-09-17 00:00:00
2010-09-18 00:00:00
2010-09-19 00:00:00
2010-09-20 00:00:00
2010-09-21 00:00:00
2010-09-22 00:00:00
2010-09-23 00:00:00
2010-09-24 00:00:00
2010-09-25 00:00:00
2010-09-26 00:00:00
2010-09-27 00:00:00
2010-09-28 00:00:00
2010-09-29 00:00:00
2010-09-30 00:00:00
2010-10-01 00:00:00
2010-10-02 00:00:00
2010-10-03 00:00:00
2010-10-04 00:00:00
2010-10-05 00:00:00
2010-10-06 00:00:00
2010-10-07 00:00:00
2010-10-08 00:00:00
2010-10-09 00:00:00
2010-10-10 00:00:00
2010-10-11 00:00:00
2010-10-12 00:00:00
2010-10-13 00:00:00
2010-10-14 00:00:00
2010-10-15 00:00:00
2010-10-16 00:00:00
2010-10-17 00:00:00
2010-10-18 00:00:00
2010-10-19 00:00:00
2010-10-20 00:00:00
2010-10-21 00:00:00
2010-10-22 00:00:00
2010-10-23 00:00:00
2010-10-24 00:00:00
2010-10-25 00:00:00
2010-10-26 00:00:00
2010-10-27 00:00:00
2010-10-28 00:00:00
2010-10-29 00:00:00
2010-10-30 00:00:00
2010-10-31 00:00:00
2010-11-01 00:00:00
2010-11-02 00:00:00
2010-11-03 00:00:00
2010-11-04 00:00:00
2010-11-05 00:00:00
2010-11-06 00:00:00
2010-11-07 00:00:00
2010-11-08 00:00:00
2010-11-09 00:00:00
2010-11-10 00:00:00
2010-11-11 00:00:00
2010-11-12 00:00:00
2010-11-13 00:00:00
2010-11-14 00:00:00
2010-11-15 00:00:00
2010-11-16 00:00:00
2010-11-17 00:00:00
2010-11-18 00:00:00
2010-11-19 00:00:00
2010-11-20 00:00:00
2010-11-21 00:00:00
2010-11-22 00:00:00
2010-11-23 00:00:00
2010-11-24 00:00:00
2010-11-25 00:00:00
2010-11-26 00:00:00
2010-11-27 00:00:00
2010-11-28 00:00:00
2010-11-29 00:00:00
2010-11-30 00:00:00
2010-12-01 00:00:00
2010-12-02 00:00:00
2010-12-03 00:00:00
2010-12-04 00:00:00
2010-12-05 00:00:00
2010-12-06 00:00:00
2010-12-07 00:00:00
2010-12-08 00:00:00
2010-12-09 00:00:00
2010-12-10 00:00:00
2010-12-11 00:00:00
2010-12-12 00:00:00
2010-12-13 00:00:00
2010-12-14 00:00:00
2010-12-15 00:00:00
2010-12-16 00:00:00
2010-12-17 00:00:00
2010-12-18 00:00:00
2010-12-19 00:00:00
2010-12-20 00:00:00
2010-12-21 00:00:00
2010-12-22 00:00:00
2010-12-23 00:00:00
2010-12-24 00:00:00
2010-12-25 00:00:00
2010-12-26 00:00:00
2010-12-27 00:00:00
2010-12-28 00:00:00
2010-12-29 00:00:00
2010-12-30 00:00:00
2010-12-31 00:00:00
2011-01-01 00:00:00
2011-01-02 00:00:00
2011-01-03 00:00:00
2011-01-04 00:00:00
2011-01-05 00:00:00
2011-01-06 00:00:00
2011-01-07 00:00:00
2011-01-08 00:00:00
2011-01-09 00:00:00
2011-01-10 00:00:00
2011-01-11 00:00:00
2011-01-12 00:00:00
2011-01-13 00:00:00
2011-01-14 00:00:00
2011-01-15 00:00:00
2011-01-16 00:00:00
2011-01-17 00:00:00
2011-01-18 00:00:00
2011-01-19 00:00:00
2011-01-20 00:00:00
2011-01-21 00:00:00
2011-01-22 00:00:00
2011-01-23 00:00:00
2011-01-24 00:00:00
2011-01-25 00:00:00
2011-01-26 00:00:00
2011-01-27 00:00:00
2011-01-28 00:00:00
2011-01-29 00:00:00
2011-01-30 00:00:00
2011-01-31 00:00:00
2011-02-01 00:00:00
2011-02-02 00:00:00
2011-02-03 00:00:00
2011-02-04 00:00:00
2011-02-05 00:00:00
2011-02-06 00:00:00
2011-02-07 00:00:00
2011-02-08 00:00:00
2011-02-09 00:00:00
2011-02-10 00:00:00
2011-02-11 00:00:00
2011-02-12 00:00:00
2011-02-13 00:00:00
2011-02-14 00:00:00
2011-02-15 00:00:00
2011-02-16 00:00:00
2011-02-17 00:00:00
2011-02-18 00:00:00
2011-02-19 00:00:00
2011-02-20 00:00:00
2011-02-21 00:00:00
2011-02-22 00:00:00
2011-02-23 00:00:00
2011-02-24 00:00:00
2011-02-25 00:00:00
2011-02-26 00:00:00
2011-02-27 00:00:00
2011-02-28 00:00:00
2011-03-01 00:00:00
2011-03-02 00:00:00
2011-03-03 00:00:00
2011-03-04 00:00:00
2011-03-05 00:00:00
2011-03-06 00:00:00
2011-03-07 00:00:00
2011-03-08 00:00:00
2011-03-09 00:00:00
2011-03-10 00:00:00
2011-03-11 00:00:00
2011-03-12 00:00:00
2011-03-13 00:00:00
2011-03-14 00:00:00
2011-03-15 00:00:00
2011-03-16 00:00:00
2011-03-17 00:00:00
2011-03-18 00:00:00
2011-03-19 00:00:00
2011-03-20 00:00:00
2011-03-21 00:00:00
2011-03-22 00:00:00
2011-03-23 00:00:00
2011-03-24 00:00:00
2011-03-25 00:00:00
2011-03-26 00:00:00
2011-03-27 00:00:00
2011-03-28 00:00:00
2011-03-29 00:00:00
2011-03-30 00:00:00
2011-03-31 00:00:00
2011-04-01 00:00:00
2011-04-02 00:00:00
2011-04-03 00:00:00
2011-04-04 00:00:00
2011-04-05 00:00:00
2011-04-06 00:00:00
2011-04-07 00:00:00
2011-04-08 00:00:00
2011-04-09 00:00:00
2011-04-10 00:00:00
2011-04-11 00:00:00
2011-04-12 00:00:00
2011-04-13 00:00:00
2011-04-14 00:00:00
2011-04-15 00:00:00
2011-04-16 00:00:00
2011-04-17 00:00:00
2011-04-18 00:00:00
2011-04-19 00:00:00
2011-04-20 00:00:00
2011-04-21 00:00:00
2011-04-22 00:00:00
2011-04-23 00:00:00
2011-04-24 00:00:00
2011-04-25 00:00:00
2011-04-26 00:00:00
2011-04-27 00:00:00
2011-04-28 00:00:00
2011-04-29 00:00:00
2011-04-30 00:00:00
2011-05-01 00:00:00
2011-05-02 00:00:00
2011-05-03 00:00:00
2011-05-04 00:00:00
2011-05-05 00:00:00
2011-05-06 00:00:00
2011-05-07 00:00:00
2011-05-08 00:00:00
2011-05-09 00:00:00
2011-05-10 00:00:00
2011-05-11 00:00:00
2011-05-12 00:00:00
2011-05-13 00:00:00
2011-05-14 00:00:00
2011-05-15 00:00:00
2011-05-16 00:00:00
2011-05-17 00:00:00
2011-05-18 00:00:00
2011-05-19 00:00:00
2011-05-20 00:00:00
2011-05-21 00:00:00
2011-05-22 00:00:00
2011-05-23 00:00:00
2011-05-24 00:00:00
2011-05-25 00:00:00
2011-05-26 00:00:00
2011-05-27 00:00:00
2011-05-28 00:00:00
2011-05-29 00:00:00
2011-05-30 00:00:00
2011-05-31 00:00:00
2011-06-01 00:00:00
2011-06-02 00:00:00
2011-06-03 00:00:00
2011-06-04 00:00:00
2011-06-05 00:00:00
2011-06-06 00:00:00
2011-06-07 00:00:00
2011-06-08 00:00:00
2011-06-09 00:00:00
2011-06-10 00:00:00
2011-06-11 00:00:00
2011-06-12 00:00:00
2011-06-13 00:00:00
2011-06-14 00:00:00
2011-06-15 00:00:00
2011-06-16 00:00:00
2011-06-17 00:00:00
2011-06-18 00:00:00
2011-06-19 00:00:00
2011-06-20 00:00:00
2011-06-21 00:00:00
2011-06-22 00:00:00
2011-06-23 00:00:00
2011-06-24 00:00:00
2011-06-25 00:00:00
2011-06-26 00:00:00
2011-06-27 00:00:00
2011-06-28 00:00:00
2011-06-29 00:00:00
2011-06-30 00:00:00
2011-07-01 00:00:00
2011-07-02 00:00:00
2011-07-03 00:00:00
2011-07-04 00:00:00
2011-07-05 00:00:00
2011-07-06 00:00:00
2011-07-07 00:00:00
2011-07-08 00:00:00
2011-07-09 00:00:00
2011-07-10 00:00:00
2011-07-11 00:00:00
2011-07-12 00:00:00
2011-07-13 00:00:00
2011-07-14 00:00:00
2011-07-15 00:00:00
2011-07-16 00:00:00
2011-07-17 00:00:00
2011-07-18 00:00:00
2011-07-19 00:00:00
2011-07-20 00:00:00
2011-07-21 00:00:00
2011-07-22 00:00:00
2011-07-23 00:00:00
2011-07-24 00:00:00
2011-07-25 00:00:00
2011-07-26 00:00:00
2011-07-27 00:00:00
2011-07-28 00:00:00
2011-07-29 00:00:00
2011-07-30 00:00:00
2011-07-31 00:00:00
2011-08-01 00:00:00
2011-08-02 00:00:00
2011-08-03 00:00:00
2011-08-04 00:00:00
2011-08-05 00:00:00
2011-08-06 00:00:00
2011-08-07 00:00:00
2011-08-08 00:00:00
2011-08-09 00:00:00
2011-08-10 00:00:00
2011-08-11 00:00:00
2011-08-12 00:00:00
2011-08-13 00:00:00
2011-08-14 00:00:00
2011-08-15 00:00:00
2011-08-16 00:00:00
2011-08-17 00:00:00
2011-08-18 00:00:00
2011-08-19 00:00:00
2011-08-20 00:00:00
2011-08-21 00:00:00
2011-08-22 00:00:00
2011-08-23 00:00:00
2011-08-24 00:00:00
2011-08-25 00:00:00
2011-08-26 00:00:00
2011-08-27 00:00:00
2011-08-28 00:00:00
2011-08-29 00:00:00
2011-08-30 00:00:00
2011-08-31 00:00:00
2011-09-01 00:00:00
2011-09-02 00:00:00
2011-09-03 00:00:00
2011-09-04 00:00:00
2011-09-05 00:00:00
2011-09-06 00:00:00
2011-09-07 00:00:00
2011-09-08 00:00:00
2011-09-09 00:00:00
2011-09-10 00:00:00
2011-09-11 00:00:00
2011-09-12 00:00:00
2011-09-13 00:00:00
2011-09-14 00:00:00
2011-09-15 00:00:00
2011-09-16 00:00:00
2011-09-17 00:00:00
2011-09-18 00:00:00
2011-09-19 00:00:00
2011-09-20 00:00:00
2011-09-21 00:00:00
2011-09-22 00:00:00
2011-09-23 00:00:00
2011-09-24 00:00:00
2011-09-25 00:00:00
2011-09-26 00:00:00
2011-09-27 00:00:00
2011-09-28 00:00:00
2011-09-29 00:00:00
2011-09-30 00:00:00
2011-10-01 00:00:00
2011-10-02 00:00:00
2011-10-03 00:00:00
2011-10-04 00:00:00
2011-10-05 00:00:00
2011-10-06 00:00:00
2011-10-07 00:00:00
2011-10-08 00:00:00
2011-10-09 00:00:00
2011-10-10 00:00:00
2011-10-11 00:00:00
2011-10-12 00:00:00
2011-10-13 00:00:00
2011-10-14 00:00:00
2011-10-15 00:00:00
2011-10-16 00:00:00
2011-10-17 00:00:00
2011-10-18 00:00:00
2011-10-19 00:00:00
2011-10-20 00:00:00
2011-10-21 00:00:00
2011-10-22 00:00:00
2011-10-23 00:00:00
2011-10-24 00:00:00
2011-10-25 00:00:00
2011-10-26 00:00:00
2011-10-27 00:00:00
2011-10-28 00:00:00
2011-10-29 00:00:00
2011-10-30 00:00:00
2011-10-31 00:00:00
2011-11-01 00:00:00
2011-11-02 00:00:00
2011-11-03 00:00:00
2011-11-04 00:00:00
2011-11-05 00:00:00
2011-11-06 00:00:00
2011-11-07 00:00:00
2011-11-08 00:00:00
2011-11-09 00:00:00
2011-11-10 00:00:00
2011-11-11 00:00:00
2011-11-12 00:00:00
2011-11-13 00:00:00
2011-11-14 00:00:00
2011-11-15 00:00:00
2011-11-16 00:00:00
2011-11-17 00:00:00
2011-11-18 00:00:00
2011-11-19 00:00:00
2011-11-20 00:00:00
2011-11-21 00:00:00
2011-11-22 00:00:00
2011-11-23 00:00:00
2011-11-24 00:00:00
2011-11-25 00:00:00
2011-11-26 00:00:00
2011-11-27 00:00:00
2011-11-28 00:00:00
2011-11-29 00:00:00
2011-11-30 00:00:00
2011-12-01 00:00:00
2011-12-02 00:00:00
2011-12-03 00:00:00
2011-12-04 00:00:00
2011-12-05 00:00:00
2011-12-06 00:00:00
2011-12-07 00:00:00
2011-12-08 00:00:00
2011-12-09 00:00:00
2011-12-10 00:00:00
2011-12-11 00:00:00
2011-12-12 00:00:00
2011-12-13 00:00:00
2011-12-14 00:00:00
2011-12-15 00:00:00
2011-12-16 00:00:00
2011-12-17 00:00:00
2011-12-18 00:00:00
2011-12-19 00:00:00
2011-12-20 00:00:00
2011-12-21 00:00:00
2011-12-22 00:00:00
2011-12-23 00:00:00
2011-12-24 00:00:00
2011-12-25 00:00:00
2011-12-26 00:00:00
2011-12-27 00:00:00
2011-12-28 00:00:00
2011-12-29 00:00:00
2011-12-30 00:00:00
2011-12-31 00:00:00
2012-01-01 00:00:00
2012-01-02 00:00:00
2012-01-03 00:00:00
2012-01-04 00:00:00
2012-01-05 00:00:00
2012-01-06 00:00:00
2012-01-07 00:00:00
2012-01-08 00:00:00
2012-01-09 00:00:00
2012-01-10 00:00:00
2012-01-11 00:00:00
2012-01-12 00:00:00
2012-01-13 00:00:00
2012-01-14 00:00:00
2012-01-15 00:00:00
2012-01-16 00:00:00
2012-01-17 00:00:00
2012-01-18 00:00:00
2012-01-19 00:00:00
2012-01-20 00:00:00
2012-01-21 00:00:00
2012-01-22 00:00:00
2012-01-23 00:00:00
2012-01-24 00:00:00
2012-01-25 00:00:00
2012-01-26 00:00:00

In [80]:
team_bs_df = pd.DataFrame(team_bs)
team_bs_df.tail()

,team,outcome,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,date
2591,Team.OKLAHOMA_CITY_THUNDER,Outcome.WIN,240,37,78,10,29,30,35,8,36,25,9,6,9,20,114,2016-12-31
2592,Team.MEMPHIS_GRIZZLIES,Outcome.WIN,240,44,87,17,35,7,9,12,28,25,6,3,7,20,112,2016-12-31
2593,Team.SACRAMENTO_KINGS,Outcome.LOSS,240,31,72,11,28,25,28,11,28,17,6,3,12,12,98,2016-12-31
2594,Team.PHOENIX_SUNS,Outcome.LOSS,240,36,87,7,17,7,10,9,32,9,6,2,9,21,86,2016-12-31
2595,Team.UTAH_JAZZ,Outcome.WIN,240,35,73,8,20,13,20,6,40,17,3,4,15,16,91,2016-12-31

In [17]:
# make 'date' the first column
date_column = team_bs_df.pop('date')
team_bs_df.insert(0, 'date', date_column)

In [18]:
# remove prefixes from categorical columns
columns_to_process = ['team', 'outcome']

for col in columns_to_process:
    team_bs_df[col] = team_bs_df[col].apply(lambda x: x.split('.')[1] if pd.notnull(x) and '.' in x else x)
    team_bs_df[col] = team_bs_df[col].str.replace('_', ' ').str.title()

In [ ]:
team_bs_df.head()

In [81]:
team_bs_df.to_csv('../data/graveyard/br_team_box_scores_2016_Jan5th_Dec31st.csv', index=False)

In [30]:
pd.DataFrame(client.team_box_scores(day=8, month=6, year=2018))

,team,outcome,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points
0,Team.GOLDEN_STATE_WARRIORS,Outcome.WIN,240,39,86,14,38,16,16,10,34,25,7,13,8,24,108
1,Team.CLEVELAND_CAVALIERS,Outcome.LOSS,240,30,87,8,27,17,25,17,27,21,5,5,11,22,85

## Player Box Scores

In [ ]:
start_time = time.time()

# initialize empty list
player_bs = []

# define start and end dates
start_date = datetime(2000, 1, 1)
end_date = datetime(2023, 12, 31)

# loop over each day in the range
current_date = start_date
while current_date <= end_date:
    
    print(current_date)
    
    # fetch data for current day
    day_data = client.player_box_scores(day=current_date.day, 
                                        month=current_date.month, 
                                        year=current_date.year)
    
    # check if day_data is not empty
    if day_data:
        # add current date to each dictionary in day_data
        for record in day_data:
            record['date'] = current_date

        # append the day's data (list of dictionaries) to team_box_scores
        player_bs.extend(day_data)

    # add time delay between requests
    time.sleep(3)
    
    # move to next day
    current_date += timedelta(days=1)

# convert list of dictionaries to a DataFrame
player_bs_df = pd.DataFrame(player_bs)

end_time = time.time()
total_time = end_time - start_time
print(f"Total time taken: {total_time} seconds")

In [ ]:
player_bs_df.to_csv('../data/graveyard/br_player_box_scores_2000_2023.csv', index=False)

In [ ]:
pd.DataFrame(client.player_box_scores(day=11, month=1, year=2024))

In [32]:
# read in each file
one = pd.read_csv("../data/graveyard/player_box_scores_2000_2008.csv")
two = pd.read_csv("../data/graveyard/player_box_scores_2009_2012_11.csv")
three = pd.read_csv("../data/graveyard/player_box_scores_2012_12_2017.csv")
four = pd.read_csv("../data/graveyard/player_box_scores_2018_2019.csv")
five = pd.read_csv("../data/graveyard/player_box_scores_2020_2023.csv")

In [33]:
# append datasets
player_bs_df = pd.concat([one, two, three, four, five], ignore_index=True)

# make 'date' the first column
date_column = player_bs_df.pop('date')
player_bs_df.insert(0, 'date', date_column)

In [34]:
# remove prefixes from categorical columns
columns_to_process = ['team', 'location', 'opponent', 'outcome']

for col in columns_to_process:
    player_bs_df[col] = player_bs_df[col].apply(lambda x: x.split('.')[1] if pd.notnull(x) and '.' in x else x)
    player_bs_df[col] = player_bs_df[col].str.replace('_', ' ').str.title()

In [ ]:
player_bs_df.dtypes

In [ ]:
player_bs_df.head()

In [37]:
player_bs_df.to_csv('../data/original/player_box_scores_2000_2023.csv', index=False)

## Season Schedule

In [ ]:
start_time = time.time()

# initialize empty list
season_schedule = []

# define start and end dates
start_date = datetime(2000, 1, 1)
end_date = datetime(2023, 12, 31)

# loop over each day in the range
current_date = start_date
while current_date <= end_date:
    
    print(current_date.year)
    
    # fetch data for current day
    year_data = client.season_schedule(season_end_year=current_date.year)
    
    # check if day_data is not empty
    if year_data:
        # add current date to each dictionary in day_data
        for record in year_data:
            record['year'] = current_date.year

        # append the year's data (list of dictionaries) to team_box_scores
        season_schedule.extend(year_data)

    # add time delay between requests
    time.sleep(30)
    
    # move to next year
    current_date = current_date.replace(year=current_date.year + 1)

# convert list of dictionaries to a DataFrame
season_schedule_df = pd.DataFrame(season_schedule)

end_time = time.time()
total_time = end_time - start_time
print(f"Total time taken: {total_time} seconds")

In [32]:
# reorder columns
season_schedule_df = season_schedule_df[['year', 'start_time', 'home_team', 
                             'away_team', 'home_team_score', 'away_team_score']]

In [33]:
# remove prefixes from categorical columns
columns_to_process = ['home_team', 'away_team']

for col in columns_to_process:
    season_schedule_df[col] = season_schedule_df[col].apply(lambda x: x.split('.')[1] if pd.notnull(x) and '.' in x else x)
    season_schedule_df[col] = season_schedule_df[col].str.replace('_', ' ').str.title()

In [45]:
season_schedule_df.to_csv('../data/original/br_season_schedule_2000_2023.csv', index=False)

In [ ]:
pd.DataFrame(client.season_schedule(season_end_year=2018))

## Play by Play

In [ ]:
season_schedule_df = pd.read_csv('../data/original/br_season_schedule_2000_2023.csv')
season_schedule_df['start_time'] = pd.to_datetime(season_schedule_df['start_time'])
celtics_home_games = season_schedule_df[season_schedule_df['home_team'] == 'Team.BOSTON_CELTICS']
celtics_home_games.head()

In [ ]:
start_time = time.time()

# initialize empty list
play_by_play = []

for current_date in celtics_home_games['start_time']:
    
    print(current_date)
    
    try:
        # Attempt to fetch data for current day
        day_data = client.play_by_play(home_team=Team.BOSTON_CELTICS,
                                       day=current_date.day, 
                                       month=current_date.month, 
                                       year=current_date.year)
        
        # If the API call is successful and day_data is not empty
        if day_data:
            # Add current date to each dictionary in day_data
            for record in day_data:
                record['date'] = current_date

            # Append the day's data (list of dictionaries) to play_by_play
            play_by_play.extend(day_data)

    except Exception as e:
        # Handle errors (print them or pass)
        print(f"Error occurred: {e}")


    # add time delay between requests
    time.sleep(30)

# convert list of dictionaries to a DataFrame
play_by_play_df = pd.DataFrame(play_by_play)

end_time = time.time()
total_time = end_time - start_time
print(f"Total time taken: {total_time} seconds")

In [72]:
play_by_play_df.to_csv('../data/original/play_by_play_2000_2023_Boston_Celtics.csv', index=False)

In [ ]:
pd.DataFrame(client.play_by_play(home_team=Team.BOSTON_CELTICS, year=1999, month=11, day=5))

# Play by Play (every day)

In [ ]:
start_time = time.time()

# initialize empty list
play_by_play_df = []

# define start and end dates
start_date = datetime(2022, 1, 1)
end_date = datetime(2023, 12, 31) 

# loop over each day in the range
current_date = start_date
while current_date <= end_date:
    
    print(current_date)
    
    try:
        # Attempt to fetch data for current day
        day_data = client.play_by_play(home_team=Team.BOSTON_CELTICS,
                                       day=current_date.day, 
                                       month=current_date.month, 
                                       year=current_date.year)
        
        # If the API call is successful and day_data is not empty
        if day_data:
            # Add current date to each dictionary in day_data
            for record in day_data:
                record['date'] = current_date

            # Append the day's data (list of dictionaries) to play_by_play
            play_by_play.extend(day_data)

    except Exception as e:
        # Handle errors (print them or pass)
        print(f"Error occurred: {e}")

    # add time delay between requests
    time.sleep(30)
    
    # move to next day
    current_date += timedelta(days=1)

# convert list of dictionaries to a DataFrame
play_by_play_df = pd.DataFrame(play_by_play_df)

end_time = time.time()
total_time = end_time - start_time
print(f"Total time taken: {total_time} seconds")

In [75]:
play_by_play_df.to_csv('../data/original/play_by_play_2022_2023_Boston_Celtics_by_day.csv', index=False)

## Standings

In [ ]:
start_time = time.time()

# initialize empty list
standings = []

# define start and end dates
start_date = datetime(2000, 1, 1)
end_date = datetime(2023, 12, 31)

# loop over each day in the range
current_date = start_date
while current_date <= end_date:
    
    print(current_date.year)
    
    # fetch data for current day
    year_data = client.standings(season_end_year=current_date.year)
    
    # check if year_data is not empty
    if year_data:
        # add current date to each dictionary in day_data
        for record in year_data:
            record['year'] = current_date.year

        # append the year's data (list of dictionaries) to team_box_scores
        standings.extend(year_data)

    # add time delay between requests
    time.sleep(30)
    
    # move to next year
    current_date = current_date.replace(year=current_date.year + 1)

# convert list of dictionaries to a DataFrame
standings_df = pd.DataFrame(standings)

end_time = time.time()
total_time = end_time - start_time
print(f"Total time taken: {total_time} seconds")

In [27]:
# reorder columns
standings_df = standings_df[['year', 'conference', 'division', 
                             'team', 'wins', 'losses']]

In [28]:
# remove prefixes from categorical columns
columns_to_process = ['team', 'division', 'conference']

for col in columns_to_process:
    standings_df[col] = standings_df[col].apply(lambda x: x.split('.')[1] if pd.notnull(x) and '.' in x else x)
    standings_df[col] = standings_df[col].str.replace('_', ' ').str.title()

In [47]:
standings_df.to_csv('../data/original/br_standings_2000_2023.csv', index=False)

In [ ]:
pd.DataFrame(client.standings(season_end_year=2019))

## Player Season Totals (Basic Stats)

In [ ]:
start_time = time.time()

# initialize empty list
players_season_totals = []

# define start and end dates
start_date = datetime(2000, 1, 1)
end_date = datetime(2023, 12, 31)

# loop over each day in the range
current_date = start_date
while current_date <= end_date:
    
    print(current_date.year)
    
    # fetch data for current day
    year_data = client.players_season_totals(season_end_year=current_date.year)
    
    # check if year_data is not empty
    if year_data:
        # add current date to each dictionary in day_data
        for record in year_data:
            record['year'] = current_date.year

        # append the year's data (list of dictionaries) to team_box_scores
        players_season_totals.extend(year_data)

    # add time delay between requests
    time.sleep(30)
    
    # move to next year
    current_date = current_date.replace(year=current_date.year + 1)

# convert list of dictionaries to a DataFrame
players_season_totals_df = pd.DataFrame(players_season_totals)

end_time = time.time()
total_time = end_time - start_time
print(f"Total time taken: {total_time} seconds")

In [56]:
# make 'year' the first column
year_column = players_season_totals_df.pop('year')
players_season_totals_df.insert(0, 'year', year_column)

In [57]:
# remove prefixes from categorical columns
columns_to_process = ['team']

for col in columns_to_process:
    players_season_totals_df[col] = players_season_totals_df[col].apply(lambda x: x.split('.')[1] if pd.notnull(x) and '.' in x else x)
    players_season_totals_df[col] = players_season_totals_df[col].str.replace('_', ' ').str.title()

In [58]:
# extract strings from 'positions' column
import re

def extract_position(text):
    '''
    Converts 'CENTER' to 'Center' and 'POWER FORWARD' to 'Power Forward'
    '''
    match = re.search(r"Position\.\w+: '([\w\s]+)'", text)
    if match:
        return match.group(1).title()  


players_season_totals_df['positions'] = players_season_totals_df['positions'].apply(extract_position)

In [ ]:
players_season_totals_df.head()

In [49]:
players_season_totals_df.to_csv('../data/original/br_players_season_totals_2000_2023.csv', index=False)

In [ ]:
pd.DataFrame(client.players_season_totals(season_end_year=2018))

## Player Season Totals (Advanced Stats)

In [ ]:
start_time = time.time()

# initialize empty list
players_season_totals_adv = []

# define start and end dates
start_date = datetime(2000, 1, 1)
end_date = datetime(2023, 12, 31)

# loop over each day in the range
current_date = start_date
while current_date <= end_date:
    
    print(current_date.year)
    
    # fetch data for current day
    year_data = client.players_advanced_season_totals(season_end_year=current_date.year)
    
    # check if year_data is not empty
    if year_data:
        # add current date to each dictionary in day_data
        for record in year_data:
            record['year'] = current_date.year

        # append the year's data (list of dictionaries) to team_box_scores
        players_season_totals_adv.extend(year_data)

    # add time delay between requests
    time.sleep(30)
    
    # move to next year
    current_date = current_date.replace(year=current_date.year + 1)

# convert list of dictionaries to a DataFrame
players_season_totals_adv_df = pd.DataFrame(players_season_totals_adv)

end_time = time.time()
total_time = end_time - start_time
print(f"Total time taken: {total_time} seconds")

In [62]:
# make 'year' the first column
year_column = players_season_totals_adv_df.pop('year')
players_season_totals_adv_df.insert(0, 'year', year_column)

In [64]:
# remove prefixes from categorical columns
columns_to_process = ['team']

for col in columns_to_process:
    players_season_totals_adv_df[col] = players_season_totals_adv_df[col].apply(lambda x: x.split('.')[1] if pd.notnull(x) and '.' in x else x)
    players_season_totals_adv_df[col] = players_season_totals_adv_df[col].str.replace('_', ' ').str.title()

In [65]:
# extract strings from 'positions' column
import re

def extract_position(text):
    '''
    Converts 'CENTER' to 'Center' and 'POWER FORWARD' to 'Power Forward'
    '''
    match = re.search(r"Position\.\w+: '([\w\s]+)'", text)
    if match:
        return match.group(1).title()  


players_season_totals_adv_df['positions'] = players_season_totals_adv_df['positions'].apply(extract_position)

In [ ]:
players_season_totals_adv_df.head()

In [51]:
players_season_totals_adv_df.to_csv('../data/original/br_players_season_totals_advanced_2000_2023.csv', index=False)

In [ ]:
pd.DataFrame(client.players_advanced_season_totals(season_end_year=2018))