# Basketball Reference API

In [1]:
import pandas as pd
from datetime import datetime, timedelta
import time

In [2]:
from basketball_reference_web_scraper import client
from basketball_reference_web_scraper.data import League, Location, Outcome, OutputType
from basketball_reference_web_scraper.data import OutputWriteOption, Position, PeriodType, Team

## Team Box Scores

In [ ]:
start_time = time.time()

# initialize empty list
team_bs = []

# define start and end dates
start_date = datetime(2000, 1, 1)
end_date = datetime(2006, 12, 31) 

# loop over each day in the range
current_date = start_date
while current_date <= end_date:
    
    print(current_date)
    
    # fetch data for current day
    day_data = client.team_box_scores(day=current_date.day, 
                                      month=current_date.month, 
                                      year=current_date.year)
    
    # check if day_data is not empty
    if day_data:
        # add current date to each dictionary in day_data
        for record in day_data:
            record['date'] = current_date

        # append the day's data (list of dictionaries) to team_box_scores
        team_bs.extend(day_data)

    # add time delay between requests
    time.sleep(5)
    
    # move to next day
    current_date += timedelta(days=1)

# convert list of dictionaries to a DataFrame
team_bs_df = pd.DataFrame(team_bs)

end_time = time.time()
total_time = end_time - start_time
print(f"Total time taken: {total_time} seconds")

In [4]:
team_bs_df.to_csv('../data/original/br_team_box_scores_2000_2006.csv', index=False)

In [ ]:
client.team_box_scores(day=1, month=2, year=2002)

## Player Box Scores

In [ ]:
start_time = time.time()

# initialize empty list
player_bs = []

# define start and end dates
start_date = datetime(2000, 1, 1)
end_date = datetime(2023, 12, 31)

# loop over each day in the range
current_date = start_date
while current_date <= end_date:
    
    print(current_date)
    
    # fetch data for current day
    day_data = client.player_box_scores(day=current_date.day, 
                                        month=current_date.month, 
                                        year=current_date.year)
    
    # check if day_data is not empty
    if day_data:
        # add current date to each dictionary in day_data
        for record in day_data:
            record['date'] = current_date

        # append the day's data (list of dictionaries) to team_box_scores
        player_bs.extend(day_data)

    # add time delay between requests
    time.sleep(3)
    
    # move to next day
    current_date += timedelta(days=1)

# convert list of dictionaries to a DataFrame
player_bs_df = pd.DataFrame(player_bs)

end_time = time.time()
total_time = end_time - start_time
print(f"Total time taken: {total_time} seconds")

In [ ]:
player_bs_df.to_csv('../data/graveyard/br_player_box_scores_2000_2023.csv', index=False)

In [ ]:
pd.DataFrame(client.player_box_scores(day=11, month=1, year=2024))

In [32]:
# read in each file
one = pd.read_csv("../data/graveyard/player_box_scores_2000_2008.csv")
two = pd.read_csv("../data/graveyard/player_box_scores_2009_2012_11.csv")
three = pd.read_csv("../data/graveyard/player_box_scores_2012_12_2017.csv")
four = pd.read_csv("../data/graveyard/player_box_scores_2018_2019.csv")
five = pd.read_csv("../data/graveyard/player_box_scores_2020_2023.csv")

In [33]:
# append datasets
player_bs_df = pd.concat([one, two, three, four, five], ignore_index=True)

# make 'date' the first column
date_column = player_bs_df.pop('date')
player_bs_df.insert(0, 'date', date_column)

In [34]:
# remove prefixes from categorical columns
columns_to_process = ['team', 'location', 'opponent', 'outcome']

for col in columns_to_process:
    player_bs_df[col] = player_bs_df[col].apply(lambda x: x.split('.')[1] if pd.notnull(x) and '.' in x else x)
    player_bs_df[col] = player_bs_df[col].str.replace('_', ' ').str.title()

In [35]:
player_bs_df.dtypes

date                                  object
slug                                  object
name                                  object
team                                  object
location                              object
opponent                              object
outcome                               object
seconds_played                         int64
made_field_goals                       int64
attempted_field_goals                  int64
made_three_point_field_goals           int64
attempted_three_point_field_goals      int64
made_free_throws                       int64
attempted_free_throws                  int64
offensive_rebounds                     int64
defensive_rebounds                     int64
assists                                int64
steals                                 int64
blocks                                 int64
turnovers                              int64
personal_fouls                         int64
game_score                           float64
dtype: object

In [36]:
player_bs_df.head()

,date,slug,name,team,location,opponent,outcome,seconds_played,made_field_goals,attempted_field_goals,...,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,game_score
0,2000-01-02,lenarvo01,Voshon Lenard,Miami Heat,Home,Orlando Magic,Win,1833,9,12,...,3,3,1,0,3,0,0,1,6,18.6
1,2000-01-02,cartean01,Anthony Carter,Miami Heat,Home,Orlando Magic,Win,2385,4,9,...,4,4,1,2,10,3,0,3,3,15.4
2,2000-01-02,majerda01,Dan Majerle,Miami Heat,Home,Orlando Magic,Win,2255,4,7,...,2,2,0,6,0,4,0,1,2,13.7
3,2000-01-02,mashbja01,Jamal Mashburn,Miami Heat,Home,Orlando Magic,Win,2359,9,22,...,3,4,2,8,4,2,0,4,2,13.6
4,2000-01-02,mournal01,Alonzo Mourning,Miami Heat,Home,Orlando Magic,Win,2559,4,18,...,13,17,2,2,3,0,7,2,5,13.4

In [37]:
player_bs_df.to_csv('../data/original/player_box_scores_2000_2023.csv', index=False)

## Season Schedule

In [15]:
pd.DataFrame(client.season_schedule(season_end_year=2018))

,start_time,away_team,home_team,away_team_score,home_team_score
0,2017-10-18 00:01:00+00:00,Team.BOSTON_CELTICS,Team.CLEVELAND_CAVALIERS,99,102
1,2017-10-18 02:30:00+00:00,Team.HOUSTON_ROCKETS,Team.GOLDEN_STATE_WARRIORS,122,121
2,2017-10-18 23:00:00+00:00,Team.CHARLOTTE_HORNETS,Team.DETROIT_PISTONS,90,102
3,2017-10-18 23:00:00+00:00,Team.BROOKLYN_NETS,Team.INDIANA_PACERS,131,140
4,2017-10-18 23:00:00+00:00,Team.MIAMI_HEAT,Team.ORLANDO_MAGIC,109,116
...,...,...,...,...,...
1307,2018-05-29 01:00:00+00:00,Team.GOLDEN_STATE_WARRIORS,Team.HOUSTON_ROCKETS,101,92
1308,2018-06-01 01:00:00+00:00,Team.CLEVELAND_CAVALIERS,Team.GOLDEN_STATE_WARRIORS,114,124
1309,2018-06-04 00:00:00+00:00,Team.CLEVELAND_CAVALIERS,Team.GOLDEN_STATE_WARRIORS,103,122
1310,2018-06-07 01:00:00+00:00,Team.GOLDEN_STATE_WARRIORS,Team.CLEVELAND_CAVALIERS,110,102
1311,2018-06-09 01:00:00+00:00,Team.GOLDEN_STATE_WARRIORS,Team.CLEVELAND_CAVALIERS,108,85

## Play by Play

In [12]:
pd.DataFrame(client.play_by_play(home_team=Team.BOSTON_CELTICS, year=2018, month=10, day=16))

,period,period_type,remaining_seconds_in_period,relevant_team,away_team,home_team,away_score,home_score,description
0,1,PeriodType.QUARTER,700.0,Team.PHILADELPHIA_76ERS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,0,0,R. Covington misses 3-pt jump shot from 27 ft
1,1,PeriodType.QUARTER,700.0,Team.BOSTON_CELTICS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,0,0,Defensive rebound by Team
2,1,PeriodType.QUARTER,675.0,Team.BOSTON_CELTICS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,0,0,J. Tatum misses 3-pt jump shot from 25 ft
3,1,PeriodType.QUARTER,673.0,Team.PHILADELPHIA_76ERS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,0,0,Defensive rebound by D. Šarić
4,1,PeriodType.QUARTER,668.0,Team.PHILADELPHIA_76ERS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,0,0,Turnover by B. Simmons (bad pass; steal by G. ...
...,...,...,...,...,...,...,...,...,...
475,4,PeriodType.QUARTER,48.0,Team.PHILADELPHIA_76ERS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,87,103,L. Shamet misses 3-pt jump shot from 25 ft
476,4,PeriodType.QUARTER,46.0,Team.BOSTON_CELTICS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,87,103,Defensive rebound by S. Ojeleye
477,4,PeriodType.QUARTER,38.0,Team.BOSTON_CELTICS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,87,105,B. Wanamaker makes 2-pt layup from 1 ft
478,4,PeriodType.QUARTER,22.0,Team.PHILADELPHIA_76ERS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,87,105,T. McConnell misses 2-pt jump shot from 7 ft
479,4,PeriodType.QUARTER,19.0,Team.BOSTON_CELTICS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,87,105,Defensive rebound by B. Wanamaker

## Standings

In [13]:
pd.DataFrame(client.standings(season_end_year=2019))

,team,wins,losses,division,conference
0,Team.TORONTO_RAPTORS,58,24,Division.ATLANTIC,Conference.EASTERN
1,Team.PHILADELPHIA_76ERS,51,31,Division.ATLANTIC,Conference.EASTERN
2,Team.BOSTON_CELTICS,49,33,Division.ATLANTIC,Conference.EASTERN
3,Team.BROOKLYN_NETS,42,40,Division.ATLANTIC,Conference.EASTERN
4,Team.NEW_YORK_KNICKS,17,65,Division.ATLANTIC,Conference.EASTERN
5,Team.MILWAUKEE_BUCKS,60,22,Division.CENTRAL,Conference.EASTERN
6,Team.INDIANA_PACERS,48,34,Division.CENTRAL,Conference.EASTERN
7,Team.DETROIT_PISTONS,41,41,Division.CENTRAL,Conference.EASTERN
8,Team.CHICAGO_BULLS,22,60,Division.CENTRAL,Conference.EASTERN
9,Team.CLEVELAND_CAVALIERS,19,63,Division.CENTRAL,Conference.EASTERN
10,Team.ORLANDO_MAGIC,42,40,Division.SOUTHEAST,Conference.EASTERN
11,Team.CHARLOTTE_HORNETS,39,43,Division.SOUTHEAST,Conference.EASTERN
12,Team.MIAMI_HEAT,39,43,Division.SOUTHEAST,Conference.EASTERN
13,Team.WASHINGTON_WIZARDS,32,50,Division.SOUTHEAST,Conference.EASTERN
14,Team.ATLANTA_HAWKS,29,53,Division.SOUTHEAST,Conference.EASTERN
15,Team.DENVER_NUGGETS,54,28,Division.NORTHWEST,Conference.WESTERN
16,Team.PORTLAND_TRAIL_BLAZERS,53,29,Division.NORTHWEST,Conference.WESTERN
17,Team.UTAH_JAZZ,50,32,Division.NORTHWEST,Conference.WESTERN
18,Team.OKLAHOMA_CITY_THUNDER,49,33,Division.NORTHWEST,Conference.WESTERN
19,Team.MINNESOTA_TIMBERWOLVES,36,46,Division.NORTHWEST,Conference.WESTERN
20,Team.GOLDEN_STATE_WARRIORS,57,25,Division.PACIFIC,Conference.WESTERN
21,Team.LOS_ANGELES_CLIPPERS,48,34,Division.PACIFIC,Conference.WESTERN
22,Team.SACRAMENTO_KINGS,39,43,Division.PACIFIC,Conference.WESTERN
23,Team.LOS_ANGELES_LAKERS,37,45,Division.PACIFIC,Conference.WESTERN
24,Team.PHOENIX_SUNS,19,63,Division.PACIFIC,Conference.WESTERN
25,Team.HOUSTON_ROCKETS,53,29,Division.SOUTHWEST,Conference.WESTERN
26,Team.SAN_ANTONIO_SPURS,48,34,Division.SOUTHWEST,Conference.WESTERN
27,Team.MEMPHIS_GRIZZLIES,33,49,Division.SOUTHWEST,Conference.WESTERN
28,Team.NEW_ORLEANS_PELICANS,33,49,Division.SOUTHWEST,Conference.WESTERN
29,Team.DALLAS_MAVERICKS,33,49,Division.SOUTHWEST,Conference.WESTERN

## Player Season Totals (Basic Stats)

In [8]:
pd.DataFrame(client.players_season_totals(season_end_year=2018))

,slug,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,...,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points
0,abrinal01,Álex Abrines,[Position.SHOOTING_GUARD],24,Team.OKLAHOMA_CITY_THUNDER,75,8,1134,115,291,...,39,46,26,88,28,38,8,25,124,353
1,acyqu01,Quincy Acy,[Position.POWER_FORWARD],27,Team.BROOKLYN_NETS,70,8,1359,130,365,...,49,60,40,217,57,33,29,60,149,411
2,adamsst01,Steven Adams,[Position.CENTER],24,Team.OKLAHOMA_CITY_THUNDER,76,76,2487,448,712,...,160,286,384,301,88,92,78,128,215,1056
3,adebaba01,Bam Adebayo,[Position.CENTER],20,Team.MIAMI_HEAT,69,19,1368,174,340,...,129,179,118,263,101,32,41,66,138,477
4,afflaar01,Arron Afflalo,[Position.SHOOTING_GUARD],32,Team.ORLANDO_MAGIC,53,3,682,65,162,...,22,26,4,62,30,4,9,21,56,179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,zellety01,Tyler Zeller,[Position.CENTER],28,Team.BROOKLYN_NETS,42,33,703,125,229,...,40,60,63,131,28,8,21,35,78,300
601,zellety01,Tyler Zeller,[Position.CENTER],28,Team.MILWAUKEE_BUCKS,24,1,406,62,105,...,17,19,47,64,19,7,14,12,48,141
602,zipsepa01,Paul Zipser,[Position.SMALL_FORWARD],23,Team.CHICAGO_BULLS,54,12,824,81,234,...,19,25,13,118,46,20,15,43,86,218
603,zizican01,Ante Žižić,[Position.CENTER],21,Team.CLEVELAND_CAVALIERS,32,2,214,49,67,...,21,29,24,36,5,2,13,11,30,119
604,zubaciv01,Ivica Zubac,[Position.CENTER],20,Team.LOS_ANGELES_LAKERS,43,0,410,61,122,...,39,51,45,78,25,8,15,26,47,161

## Player Season Totals (Advanced Stats)

In [11]:
pd.DataFrame(client.players_advanced_season_totals(season_end_year=2018))

,slug,name,positions,age,team,games_played,minutes_played,player_efficiency_rating,true_shooting_percentage,three_point_attempt_rate,...,usage_percentage,offensive_win_shares,defensive_win_shares,win_shares,win_shares_per_48_minutes,offensive_box_plus_minus,defensive_box_plus_minus,box_plus_minus,value_over_replacement_player,is_combined_totals
0,abrinal01,Álex Abrines,[Position.SHOOTING_GUARD],24,Team.OKLAHOMA_CITY_THUNDER,75,1134,9.0,0.567,0.759,...,12.7,1.3,1.0,2.2,0.094,-1.9,0.4,-1.5,0.1,False
1,acyqu01,Quincy Acy,[Position.POWER_FORWARD],27,Team.BROOKLYN_NETS,70,1359,8.2,0.525,0.800,...,14.4,-0.1,1.1,1.0,0.036,-2.6,0.1,-2.5,-0.2,False
2,adamsst01,Steven Adams,[Position.CENTER],24,Team.OKLAHOMA_CITY_THUNDER,76,2487,20.6,0.630,0.003,...,16.7,6.7,3.0,9.7,0.187,1.7,-0.6,1.1,2.0,False
3,adebaba01,Bam Adebayo,[Position.CENTER],20,Team.MIAMI_HEAT,69,1368,15.7,0.570,0.021,...,15.9,2.3,1.9,4.2,0.148,-1.1,0.7,-0.4,0.6,False
4,afflaar01,Arron Afflalo,[Position.SHOOTING_GUARD],32,Team.ORLANDO_MAGIC,53,682,5.8,0.516,0.432,...,12.5,-0.1,0.2,0.1,0.009,-3.8,-1.5,-5.4,-0.6,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,zellety01,Tyler Zeller,[Position.CENTER],28,Team.BROOKLYN_NETS,42,703,15.3,0.587,0.114,...,17.9,1.0,0.6,1.5,0.105,-0.7,-0.4,-1.0,0.2,False
601,zellety01,Tyler Zeller,[Position.CENTER],28,Team.MILWAUKEE_BUCKS,24,406,17.1,0.622,0.019,...,13.9,1.1,0.3,1.4,0.163,-0.3,-1.8,-2.1,0.0,False
602,zipsepa01,Paul Zipser,[Position.SMALL_FORWARD],23,Team.CHICAGO_BULLS,54,824,5.2,0.445,0.470,...,15.2,-1.1,0.6,-0.6,-0.034,-5.5,-0.5,-6.1,-0.8,False
603,zizican01,Ante Žižić,[Position.CENTER],21,Team.CLEVELAND_CAVALIERS,32,214,24.2,0.746,0.000,...,18.8,0.9,0.2,1.0,0.231,1.9,-0.9,1.0,0.2,False
604,zubaciv01,Ivica Zubac,[Position.CENTER],20,Team.LOS_ANGELES_LAKERS,43,410,15.3,0.557,0.008,...,17.6,0.5,0.5,1.0,0.118,-1.8,-0.3,-2.0,0.0,False