In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd

In [3]:
from spam_data.api.cache_filler import load_or_fetch_from_cache, clear_cache
from spam_data.api import THIRTY_YEARS_DASH_STATS, RECENT_GAMES_BOX_SCORES

In [4]:
# clear_cache(THIRTY_YEARS_DASH_STATS)

In [5]:
df = load_or_fetch_from_cache(THIRTY_YEARS_DASH_STATS)

In [6]:
df.head()

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,...,DREB_PCT_RANK,REB_PCT_RANK,TM_TOV_PCT_RANK,EFG_PCT_RANK,TS_PCT_RANK,PACE_RANK,PIE_RANK,SEASON,MONTH,CALENDAR_MONTH
0,1610612737,Atlanta Hawks,16,9,7,0.563,768.0,96.6,98.3,95.3,...,12,16,20,20,20,26,15,1996-97,2,11
1,1610612738,Boston Celtics,14,4,10,0.286,672.0,96.9,98.4,104.2,...,11,19,15,21,21,3,27,1996-97,2,11
2,1610612766,Charlotte Hornets,14,8,6,0.571,672.0,104.1,105.4,104.2,...,15,21,7,6,7,25,11,1996-97,2,11
3,1610612741,Chicago Bulls,16,15,1,0.938,768.0,109.0,110.5,92.0,...,2,4,1,5,8,8,1,1996-97,2,11
4,1610612739,Cleveland Cavaliers,14,9,5,0.643,677.0,100.7,101.3,93.4,...,5,14,10,12,13,28,6,1996-97,2,11

In [7]:
df.columns

Index(['TEAM_ID', 'TEAM_NAME', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'E_OFF_RATING',
       'OFF_RATING', 'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING',
       'NET_RATING', 'AST_PCT', 'AST_TO', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT',
       'REB_PCT', 'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT', 'E_PACE', 'PACE',
       'PACE_PER40', 'POSS', 'PIE', 'GP_RANK', 'W_RANK', 'L_RANK',
       'W_PCT_RANK', 'MIN_RANK', 'OFF_RATING_RANK', 'DEF_RATING_RANK',
       'NET_RATING_RANK', 'AST_PCT_RANK', 'AST_TO_RANK', 'AST_RATIO_RANK',
       'OREB_PCT_RANK', 'DREB_PCT_RANK', 'REB_PCT_RANK', 'TM_TOV_PCT_RANK',
       'EFG_PCT_RANK', 'TS_PCT_RANK', 'PACE_RANK', 'PIE_RANK', 'SEASON',
       'MONTH', 'CALENDAR_MONTH'],
      dtype='object')

## BASE BUILDER

In [8]:
from spam_data.feature_engineering.base_builder import create_base_with_targets

Season 2021-22: 1230 games
Season 2022-23: 1230 games
Season 2023-24: 860 games
Season 2021-22: 1222 games
Season 2022-23: 1221 games
Season 2023-24: 851 games
Season 2021-22: 1230 games
Season 2022-23: 1230 games
Season 2023-24: 860 games
Season 2021-22: 1222 games
Season 2022-23: 1221 games
Season 2023-24: 851 games

C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\utility_functions.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])
C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\utility_functions.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])

In [9]:
base_df = create_base_with_targets()

Season 2021-22: 1230 games
Season 2022-23: 1230 games
Season 2023-24: 860 games
Season 2021-22: 1222 games
Season 2022-23: 1221 games
Season 2023-24: 851 games

C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\utility_functions.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])

In [10]:
base_df.head()

,SEASON_ID,HOME_TEAM_ID,HOME_TEAM_ABBREVIATION,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_ID,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS
0,2021-22,1610612737,ATL,Atlanta Hawks,1610612764,WAS,Washington Wizards,22101192,2022-04-06,118,103,1,221,15.0
1,2021-22,1610612737,ATL,Atlanta Hawks,1610612751,BKN,Brooklyn Nets,22101163,2022-04-02,122,115,1,237,7.0
2,2021-22,1610612737,ATL,Atlanta Hawks,1610612739,CLE,Cleveland Cavaliers,22100452,2022-03-31,131,107,1,238,24.0
3,2021-22,1610612737,ATL,Atlanta Hawks,1610612744,GSW,Golden State Warriors,22101102,2022-03-25,121,110,1,231,11.0
4,2021-22,1610612737,ATL,Atlanta Hawks,1610612740,NOP,New Orleans Pelicans,22101064,2022-03-20,112,117,0,229,-5.0

In [11]:
base_df.GAME_DATE

0      2022-04-06
1      2022-04-02
2      2022-03-31
3      2022-03-25
4      2022-03-20
          ...
3289   2023-11-14
3290   2023-11-08
3291   2023-10-30
3292   2023-10-27
3293   2023-10-25
Name: GAME_DATE, Length: 3294, dtype: datetime64[ns]

In [12]:
base_df["MONTH"] = base_df.GAME_DATE.dt.month
base_df["PREV_MONTH"] = base_df.MONTH.apply(lambda x: x - 1 if x > 1 else 12)

In [13]:
base_df.head()

,SEASON_ID,HOME_TEAM_ID,HOME_TEAM_ABBREVIATION,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_ID,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS,MONTH,PREV_MONTH
0,2021-22,1610612737,ATL,Atlanta Hawks,1610612764,WAS,Washington Wizards,22101192,2022-04-06,118,103,1,221,15.0,4,3
1,2021-22,1610612737,ATL,Atlanta Hawks,1610612751,BKN,Brooklyn Nets,22101163,2022-04-02,122,115,1,237,7.0,4,3
2,2021-22,1610612737,ATL,Atlanta Hawks,1610612739,CLE,Cleveland Cavaliers,22100452,2022-03-31,131,107,1,238,24.0,3,2
3,2021-22,1610612737,ATL,Atlanta Hawks,1610612744,GSW,Golden State Warriors,22101102,2022-03-25,121,110,1,231,11.0,3,2
4,2021-22,1610612737,ATL,Atlanta Hawks,1610612740,NOP,New Orleans Pelicans,22101064,2022-03-20,112,117,0,229,-5.0,3,2

In [14]:
base_df.columns

Index(['SEASON_ID', 'HOME_TEAM_ID', 'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_NAME',
       'AWAY_TEAM_ID', 'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'HOME_PTS', 'AWAY_PTS', 'GAME_RESULT', 'TOTAL_PTS',
       'PLUS_MINUS', 'MONTH', 'PREV_MONTH'],
      dtype='object')

In [15]:
df.columns

Index(['TEAM_ID', 'TEAM_NAME', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'E_OFF_RATING',
       'OFF_RATING', 'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING',
       'NET_RATING', 'AST_PCT', 'AST_TO', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT',
       'REB_PCT', 'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT', 'E_PACE', 'PACE',
       'PACE_PER40', 'POSS', 'PIE', 'GP_RANK', 'W_RANK', 'L_RANK',
       'W_PCT_RANK', 'MIN_RANK', 'OFF_RATING_RANK', 'DEF_RATING_RANK',
       'NET_RATING_RANK', 'AST_PCT_RANK', 'AST_TO_RANK', 'AST_RATIO_RANK',
       'OREB_PCT_RANK', 'DREB_PCT_RANK', 'REB_PCT_RANK', 'TM_TOV_PCT_RANK',
       'EFG_PCT_RANK', 'TS_PCT_RANK', 'PACE_RANK', 'PIE_RANK', 'SEASON',
       'MONTH', 'CALENDAR_MONTH'],
      dtype='object')

In [16]:
merged = base_df.merge(df, left_on=["SEASON_ID", "HOME_TEAM_ID", "PREV_MONTH"], right_on=["SEASON", "TEAM_ID", "CALENDAR_MONTH"])

In [17]:
merged

,SEASON_ID,HOME_TEAM_ID,HOME_TEAM_ABBREVIATION,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_ID,GAME_DATE,HOME_PTS,...,DREB_PCT_RANK,REB_PCT_RANK,TM_TOV_PCT_RANK,EFG_PCT_RANK,TS_PCT_RANK,PACE_RANK,PIE_RANK,SEASON,MONTH_y,CALENDAR_MONTH
0,2021-22,1610612737,ATL,Atlanta Hawks,1610612764,WAS,Washington Wizards,22101192,2022-04-06,118,...,22,21,1,12,8,16,12,2021-22,6,3
1,2021-22,1610612737,ATL,Atlanta Hawks,1610612751,BKN,Brooklyn Nets,22101163,2022-04-02,122,...,22,21,1,12,8,16,12,2021-22,6,3
2,2021-22,1610612737,ATL,Atlanta Hawks,1610612739,CLE,Cleveland Cavaliers,22100452,2022-03-31,131,...,9,6,5,14,13,16,15,2021-22,5,2
3,2021-22,1610612737,ATL,Atlanta Hawks,1610612744,GSW,Golden State Warriors,22101102,2022-03-25,121,...,9,6,5,14,13,16,15,2021-22,5,2
4,2021-22,1610612737,ATL,Atlanta Hawks,1610612740,NOP,New Orleans Pelicans,22101064,2022-03-20,112,...,9,6,5,14,13,16,15,2021-22,5,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3043,2023-24,1610612766,CHA,Charlotte Hornets,1610612738,BOS,Boston Celtics,22300217,2023-11-20,121,...,22,21,18,22,17,2,18,2023-24,1,10
3044,2023-24,1610612766,CHA,Charlotte Hornets,1610612752,NYK,New York Knicks,22300202,2023-11-18,108,...,22,21,18,22,17,2,18,2023-24,1,10
3045,2023-24,1610612766,CHA,Charlotte Hornets,1610612749,MIL,Milwaukee Bucks,22300027,2023-11-17,99,...,22,21,18,22,17,2,18,2023-24,1,10
3046,2023-24,1610612766,CHA,Charlotte Hornets,1610612748,MIA,Miami Heat,22300017,2023-11-14,105,...,22,21,18,22,17,2,18,2023-24,1,10
3047,2023-24,1610612766,CHA,Charlotte Hornets,1610612764,WAS,Washington Wizards,22300157,2023-11-08,116,...,22,21,18,22,17,2,18,2023-24,1,10

In [18]:
drop_list = ["TEAM_ID", "TEAM_NAME", "GP", "W", "L", "W_PCT", "MIN", "SEASON", "MONTH_x", "MONTH_y"]

In [19]:
merged = merged.drop(columns=drop_list)

In [20]:
merged.columns

Index(['SEASON_ID', 'HOME_TEAM_ID', 'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_NAME',
       'AWAY_TEAM_ID', 'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'HOME_PTS', 'AWAY_PTS', 'GAME_RESULT', 'TOTAL_PTS',
       'PLUS_MINUS', 'PREV_MONTH', 'E_OFF_RATING', 'OFF_RATING',
       'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT',
       'AST_TO', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT',
       'EFG_PCT', 'TS_PCT', 'E_PACE', 'PACE', 'PACE_PER40', 'POSS', 'PIE',
       'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK',
       'OFF_RATING_RANK', 'DEF_RATING_RANK', 'NET_RATING_RANK', 'AST_PCT_RANK',
       'AST_TO_RANK', 'AST_RATIO_RANK', 'OREB_PCT_RANK', 'DREB_PCT_RANK',
       'REB_PCT_RANK', 'TM_TOV_PCT_RANK', 'EFG_PCT_RANK', 'TS_PCT_RANK',
       'PACE_RANK', 'PIE_RANK', 'CALENDAR_MONTH'],
      dtype='object')

In [21]:
merged = merged.rename(columns=lambda x: f"HOME_{x}" if x in df.columns else x)

In [22]:
merged.columns

Index(['SEASON_ID', 'HOME_TEAM_ID', 'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_NAME',
       'AWAY_TEAM_ID', 'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'HOME_PTS', 'AWAY_PTS', 'GAME_RESULT', 'TOTAL_PTS',
       'PLUS_MINUS', 'PREV_MONTH', 'HOME_E_OFF_RATING', 'HOME_OFF_RATING',
       'HOME_E_DEF_RATING', 'HOME_DEF_RATING', 'HOME_E_NET_RATING',
       'HOME_NET_RATING', 'HOME_AST_PCT', 'HOME_AST_TO', 'HOME_AST_RATIO',
       'HOME_OREB_PCT', 'HOME_DREB_PCT', 'HOME_REB_PCT', 'HOME_TM_TOV_PCT',
       'HOME_EFG_PCT', 'HOME_TS_PCT', 'HOME_E_PACE', 'HOME_PACE',
       'HOME_PACE_PER40', 'HOME_POSS', 'HOME_PIE', 'HOME_GP_RANK',
       'HOME_W_RANK', 'HOME_L_RANK', 'HOME_W_PCT_RANK', 'HOME_MIN_RANK',
       'HOME_OFF_RATING_RANK', 'HOME_DEF_RATING_RANK', 'HOME_NET_RATING_RANK',
       'HOME_AST_PCT_RANK', 'HOME_AST_TO_RANK', 'HOME_AST_RATIO_RANK',
       'HOME_OREB_PCT_RANK', 'HOME_DREB_PCT_RANK', 'HOME_REB_PCT_RANK',
       'HOME_TM_TOV_PCT_RANK', 'HOME_EFG_PCT_RANK', 'HOME_TS_PCT_RANK',
       'HOME_PACE_RANK', 'HOME_PIE_RANK', 'HOME_CALENDAR_MONTH'],
      dtype='object')

In [38]:
merged = merged.merge(df, left_on=["SEASON_ID", "AWAY_TEAM_ID", "PREV_MONTH"], right_on=["SEASON", "TEAM_ID", "CALENDAR_MONTH"])

In [40]:
merged = merged.rename(columns=lambda x: f"AWAY_{x}" if x in df.columns else x)

In [23]:
merged.columns

Index(['SEASON_ID', 'HOME_TEAM_ID', 'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_NAME',
       'AWAY_TEAM_ID', 'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'HOME_PTS', 'AWAY_PTS', 'GAME_RESULT', 'TOTAL_PTS',
       'PLUS_MINUS', 'PREV_MONTH', 'HOME_E_OFF_RATING', 'HOME_OFF_RATING',
       'HOME_E_DEF_RATING', 'HOME_DEF_RATING', 'HOME_E_NET_RATING',
       'HOME_NET_RATING', 'HOME_AST_PCT', 'HOME_AST_TO', 'HOME_AST_RATIO',
       'HOME_OREB_PCT', 'HOME_DREB_PCT', 'HOME_REB_PCT', 'HOME_TM_TOV_PCT',
       'HOME_EFG_PCT', 'HOME_TS_PCT', 'HOME_E_PACE', 'HOME_PACE',
       'HOME_PACE_PER40', 'HOME_POSS', 'HOME_PIE', 'HOME_GP_RANK',
       'HOME_W_RANK', 'HOME_L_RANK', 'HOME_W_PCT_RANK', 'HOME_MIN_RANK',
       'HOME_OFF_RATING_RANK', 'HOME_DEF_RATING_RANK', 'HOME_NET_RATING_RANK',
       'HOME_AST_PCT_RANK', 'HOME_AST_TO_RANK', 'HOME_AST_RATIO_RANK',
       'HOME_OREB_PCT_RANK', 'HOME_DREB_PCT_RANK', 'HOME_REB_PCT_RANK',
       'HOME_TM_TOV_PCT_RANK', 'HOME_EFG_PCT_RANK', 'HOME_TS_PCT_RANK',
       'HOME_PACE_RANK', 'HOME_PIE_RANK', 'HOME_CALENDAR_MONTH'],
      dtype='object')

In [42]:
df.columns

Index(['TEAM_ID', 'TEAM_NAME', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'E_OFF_RATING',
       'OFF_RATING', 'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING',
       'NET_RATING', 'AST_PCT', 'AST_TO', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT',
       'REB_PCT', 'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT', 'E_PACE', 'PACE',
       'PACE_PER40', 'POSS', 'PIE', 'GP_RANK', 'W_RANK', 'L_RANK',
       'W_PCT_RANK', 'MIN_RANK', 'OFF_RATING_RANK', 'DEF_RATING_RANK',
       'NET_RATING_RANK', 'AST_PCT_RANK', 'AST_TO_RANK', 'AST_RATIO_RANK',
       'OREB_PCT_RANK', 'DREB_PCT_RANK', 'REB_PCT_RANK', 'TM_TOV_PCT_RANK',
       'EFG_PCT_RANK', 'TS_PCT_RANK', 'PACE_RANK', 'PIE_RANK', 'SEASON',
       'MONTH', 'CALENDAR_MONTH'],
      dtype='object')

In [47]:
drop_list = ["TEAM_ID", "TEAM_NAME", "GP", "W", "L", "W_PCT", "MIN", "SEASON", "MONTH_x", "MONTH_y"]

In [44]:
base_df.columns

Index(['SEASON_ID', 'HOME_TEAM_ID', 'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_NAME',
       'AWAY_TEAM_ID', 'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'HOME_PTS', 'AWAY_PTS', 'GAME_RESULT', 'TOTAL_PTS',
       'PLUS_MINUS', 'MONTH', 'PREV_MONTH'],
      dtype='object')

In [45]:
set(base_df.columns) & set(df.columns)

{'MONTH'}

In [43]:
merged.columns

Index(['SEASON_ID', 'HOME_TEAM_ID', 'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_NAME',
       'AWAY_TEAM_ID', 'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'HOME_PTS',
       ...
       'AWAY_DREB_PCT_RANK', 'AWAY_REB_PCT_RANK', 'AWAY_TM_TOV_PCT_RANK',
       'AWAY_EFG_PCT_RANK', 'AWAY_TS_PCT_RANK', 'AWAY_PACE_RANK',
       'AWAY_PIE_RANK', 'AWAY_SEASON', 'AWAY_MONTH', 'AWAY_CALENDAR_MONTH'],
      dtype='object', length=114)

In [41]:
merged

,SEASON_ID,HOME_TEAM_ID,HOME_TEAM_ABBREVIATION,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_ID,GAME_DATE,HOME_PTS,...,AWAY_DREB_PCT_RANK,AWAY_REB_PCT_RANK,AWAY_TM_TOV_PCT_RANK,AWAY_EFG_PCT_RANK,AWAY_TS_PCT_RANK,AWAY_PACE_RANK,AWAY_PIE_RANK,AWAY_SEASON,AWAY_MONTH,AWAY_CALENDAR_MONTH
0,2021-22,1610612737,ATL,Atlanta Hawks,1610612764,WAS,Washington Wizards,22101192,2022-04-06,118,...,9,19,8,13,10,18,14,2021-22,6,3
1,2021-22,1610612737,ATL,Atlanta Hawks,1610612751,BKN,Brooklyn Nets,22101163,2022-04-02,122,...,30,20,26,1,1,14,5,2021-22,6,3
2,2021-22,1610612737,ATL,Atlanta Hawks,1610612739,CLE,Cleveland Cavaliers,22100452,2022-03-31,131,...,21,14,28,18,17,27,12,2021-22,5,2
3,2021-22,1610612737,ATL,Atlanta Hawks,1610612744,GSW,Golden State Warriors,22101102,2022-03-25,121,...,8,16,7,10,12,22,10,2021-22,5,2
4,2021-22,1610612737,ATL,Atlanta Hawks,1610612740,NOP,New Orleans Pelicans,22101064,2022-03-20,112,...,23,5,27,8,5,24,6,2021-22,5,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3043,2023-24,1610612766,CHA,Charlotte Hornets,1610612738,BOS,Boston Celtics,22300217,2023-11-20,121,...,16,6,21,6,9,20,5,2023-24,1,10
3044,2023-24,1610612766,CHA,Charlotte Hornets,1610612752,NYK,New York Knicks,22300202,2023-11-18,108,...,3,4,20,26,25,19,15,2023-24,1,10
3045,2023-24,1610612766,CHA,Charlotte Hornets,1610612749,MIL,Milwaukee Bucks,22300027,2023-11-17,99,...,5,13,26,7,6,3,23,2023-24,1,10
3046,2023-24,1610612766,CHA,Charlotte Hornets,1610612748,MIA,Miami Heat,22300017,2023-11-14,105,...,25,28,5,24,21,23,20,2023-24,1,10
3047,2023-24,1610612766,CHA,Charlotte Hornets,1610612764,WAS,Washington Wizards,22300157,2023-11-08,116,...,24,27,7,18,18,1,24,2023-24,1,10