In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import spam_data

In [3]:
from spam_data.api.game_stats import *

In [3]:
from spam_data.api.team_stats import *

In [4]:
df = get_games()

In [5]:
team = get_teams()

In [6]:
team

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976
23,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974
26,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988

In [8]:
df

,SEASON_ID_AWAY,TEAM_ID_AWAY,TEAM_ABBREVIATION_AWAY,TEAM_NAME_AWAY,GAME_ID,GAME_DATE_AWAY,MATCHUP_AWAY,WL_AWAY,MIN_AWAY,FGM_AWAY,...,DREB_HOME,REB_HOME,AST_HOME,STL_HOME,BLK_HOME,TOV_HOME,PF_HOME,PTS_HOME,PLUS_MINUS_HOME,VIDEO_AVAILABLE_HOME
0,22023,1610612747,LAL,Los Angeles Lakers,0022300061,2023-10-24,LAL @ DEN,L,240,41,...,33,42,29,9,6,12,15,119,12,1
2,22023,1610612756,PHX,Phoenix Suns,0022300062,2023-10-24,PHX @ GSW,W,240,42,...,31,49,19,11,6,11,23,104,-4,1
4,22023,1610612765,DET,Detroit Pistons,0022300068,2023-10-25,DET @ MIA,L,240,41,...,32,48,22,11,3,7,18,103,1,1
6,22023,1610612757,POR,Portland Trail Blazers,0022300074,2023-10-25,POR @ LAC,L,240,44,...,31,45,36,11,7,18,20,123,12,1
8,22023,1610612745,HOU,Houston Rockets,0022300066,2023-10-25,HOU @ ORL,L,240,32,...,40,57,19,8,6,16,20,116,30,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1805,22023,1610612746,LAC,LA Clippers,0022300873,2024-03-03,LAC @ MIN,W,240,32,...,42,54,24,4,7,15,14,88,-1,1
1807,22023,1610612765,DET,Detroit Pistons,0022300874,2024-03-03,DET @ ORL,L,240,33,...,41,48,24,7,6,22,16,113,22,1
1808,22023,1610612766,CHA,Charlotte Hornets,0022300875,2024-03-03,CHA @ TOR,L,240,43,...,34,45,27,8,6,16,16,111,5,1
1809,22023,1610612752,NYK,New York Knicks,0022300876,2024-03-03,NYK @ CLE,W,240,42,...,29,39,31,7,5,11,11,98,-9,1
1811,22023,1610612754,IND,Indiana Pacers,0022300877,2024-03-03,IND @ SAS,L,240,41,...,35,45,33,6,8,16,17,117,12,1

# Base Feature Test

In [7]:
from spam_data.feature_engineering import base_builder

Season 2021-22: 1230 games
Season 2022-23: 1230 games
Season 2023-24: 860 games
Season 2021-22: 1222 games
Season 2022-23: 1221 games
Season 2023-24: 851 games

C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\utility_functions.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])

In [8]:
x = base_builder.reshape_box_scores_to_matchups()

Season 2021-22: 1230 games
Season 2022-23: 1230 games
Season 2023-24: 860 games
Season 2021-22: 1222 games
Season 2022-23: 1221 games
Season 2023-24: 851 games

C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\utility_functions.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])

In [11]:
x.columns

Index(['SEASON_ID', 'HOME_TEAM_ID', 'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_NAME',
       'GAME_ID', 'GAME_DATE', 'HOME_WL', 'HOME_MIN', 'HOME_PTS', 'HOME_FGM',
       'HOME_FGA', 'HOME_FG_PCT', 'HOME_FG3M', 'HOME_FG3A', 'HOME_FG3_PCT',
       'HOME_FTM', 'HOME_FTA', 'HOME_FT_PCT', 'HOME_OREB', 'HOME_DREB',
       'HOME_REB', 'HOME_AST', 'HOME_STL', 'HOME_BLK', 'HOME_TOV', 'HOME_PF',
       'PLUS_MINUS', 'AWAY_TEAM_ID', 'AWAY_TEAM_ABBREVIATION',
       'AWAY_TEAM_NAME', 'AWAY_WL', 'AWAY_MIN', 'AWAY_PTS', 'AWAY_FGM',
       'AWAY_FGA', 'AWAY_FG_PCT', 'AWAY_FG3M', 'AWAY_FG3A', 'AWAY_FG3_PCT',
       'AWAY_FTM', 'AWAY_FTA', 'AWAY_FT_PCT', 'AWAY_OREB', 'AWAY_DREB',
       'AWAY_REB', 'AWAY_AST', 'AWAY_STL', 'AWAY_BLK', 'AWAY_TOV', 'AWAY_PF',
       'GAME_RESULT', 'TOTAL_PTS'],
      dtype='object')

In [12]:
df = base_builder.create_base_with_targets()

Season 2021-22: 1230 games
Season 2022-23: 1230 games
Season 2023-24: 860 games
Season 2021-22: 1222 games
Season 2022-23: 1221 games
Season 2023-24: 851 games

C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\utility_functions.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])

In [13]:
df

,SEASON_ID,HOME_TEAM_ID,HOME_TEAM_ABBREVIATION,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_ID,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS
0,2021-22,1610612737,ATL,Atlanta Hawks,1610612764,WAS,Washington Wizards,22101192,2022-04-06,118,103,1,221,15.0
1,2021-22,1610612737,ATL,Atlanta Hawks,1610612751,BKN,Brooklyn Nets,22101163,2022-04-02,122,115,1,237,7.0
2,2021-22,1610612737,ATL,Atlanta Hawks,1610612739,CLE,Cleveland Cavaliers,22100452,2022-03-31,131,107,1,238,24.0
3,2021-22,1610612737,ATL,Atlanta Hawks,1610612744,GSW,Golden State Warriors,22101102,2022-03-25,121,110,1,231,11.0
4,2021-22,1610612737,ATL,Atlanta Hawks,1610612740,NOP,New Orleans Pelicans,22101064,2022-03-20,112,117,0,229,-5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3289,2023-24,1610612766,CHA,Charlotte Hornets,1610612748,MIA,Miami Heat,22300017,2023-11-14,105,111,0,216,-6.0
3290,2023-24,1610612766,CHA,Charlotte Hornets,1610612764,WAS,Washington Wizards,22300157,2023-11-08,116,132,0,248,-16.0
3291,2023-24,1610612766,CHA,Charlotte Hornets,1610612751,BKN,Brooklyn Nets,22300101,2023-10-30,121,133,0,254,-12.0
3292,2023-24,1610612766,CHA,Charlotte Hornets,1610612765,DET,Detroit Pistons,22300077,2023-10-27,99,111,0,210,-12.0
3293,2023-24,1610612766,CHA,Charlotte Hornets,1610612737,ATL,Atlanta Hawks,22300063,2023-10-25,116,110,1,226,6.0

In [14]:
base_columns = ["SEASON_ID", "TEAM_ID", "TEAM_ABBREVIATION", "TEAM_NAME", "GAME_ID", "GAME_DATE", "MATCHUP", "WL", "MIN", ""]

In [15]:
df.columns

Index(['SEASON_ID', 'HOME_TEAM_ID', 'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_NAME',
       'AWAY_TEAM_ID', 'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'HOME_PTS', 'AWAY_PTS', 'GAME_RESULT', 'TOTAL_PTS',
       'PLUS_MINUS'],
      dtype='object')

In [16]:
df.head()

,SEASON_ID,HOME_TEAM_ID,HOME_TEAM_ABBREVIATION,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_ID,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS
0,2021-22,1610612737,ATL,Atlanta Hawks,1610612764,WAS,Washington Wizards,22101192,2022-04-06,118,103,1,221,15.0
1,2021-22,1610612737,ATL,Atlanta Hawks,1610612751,BKN,Brooklyn Nets,22101163,2022-04-02,122,115,1,237,7.0
2,2021-22,1610612737,ATL,Atlanta Hawks,1610612739,CLE,Cleveland Cavaliers,22100452,2022-03-31,131,107,1,238,24.0
3,2021-22,1610612737,ATL,Atlanta Hawks,1610612744,GSW,Golden State Warriors,22101102,2022-03-25,121,110,1,231,11.0
4,2021-22,1610612737,ATL,Atlanta Hawks,1610612740,NOP,New Orleans Pelicans,22101064,2022-03-20,112,117,0,229,-5.0

In [17]:
df

,SEASON_ID,HOME_TEAM_ID,HOME_TEAM_ABBREVIATION,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_ID,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS
0,2021-22,1610612737,ATL,Atlanta Hawks,1610612764,WAS,Washington Wizards,22101192,2022-04-06,118,103,1,221,15.0
1,2021-22,1610612737,ATL,Atlanta Hawks,1610612751,BKN,Brooklyn Nets,22101163,2022-04-02,122,115,1,237,7.0
2,2021-22,1610612737,ATL,Atlanta Hawks,1610612739,CLE,Cleveland Cavaliers,22100452,2022-03-31,131,107,1,238,24.0
3,2021-22,1610612737,ATL,Atlanta Hawks,1610612744,GSW,Golden State Warriors,22101102,2022-03-25,121,110,1,231,11.0
4,2021-22,1610612737,ATL,Atlanta Hawks,1610612740,NOP,New Orleans Pelicans,22101064,2022-03-20,112,117,0,229,-5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3289,2023-24,1610612766,CHA,Charlotte Hornets,1610612748,MIA,Miami Heat,22300017,2023-11-14,105,111,0,216,-6.0
3290,2023-24,1610612766,CHA,Charlotte Hornets,1610612764,WAS,Washington Wizards,22300157,2023-11-08,116,132,0,248,-16.0
3291,2023-24,1610612766,CHA,Charlotte Hornets,1610612751,BKN,Brooklyn Nets,22300101,2023-10-30,121,133,0,254,-12.0
3292,2023-24,1610612766,CHA,Charlotte Hornets,1610612765,DET,Detroit Pistons,22300077,2023-10-27,99,111,0,210,-12.0
3293,2023-24,1610612766,CHA,Charlotte Hornets,1610612737,ATL,Atlanta Hawks,22300063,2023-10-25,116,110,1,226,6.0

In [18]:
df = base_builder.create_base_with_targets()

Season 2021-22: 1230 games
Season 2022-23: 1230 games
Season 2023-24: 860 games
Season 2021-22: 1222 games
Season 2022-23: 1221 games
Season 2023-24: 851 games

C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\utility_functions.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])

In [19]:
df

,SEASON_ID,HOME_TEAM_ID,HOME_TEAM_ABBREVIATION,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_ID,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS
0,2021-22,1610612737,ATL,Atlanta Hawks,1610612764,WAS,Washington Wizards,22101192,2022-04-06,118,103,1,221,15.0
1,2021-22,1610612737,ATL,Atlanta Hawks,1610612751,BKN,Brooklyn Nets,22101163,2022-04-02,122,115,1,237,7.0
2,2021-22,1610612737,ATL,Atlanta Hawks,1610612739,CLE,Cleveland Cavaliers,22100452,2022-03-31,131,107,1,238,24.0
3,2021-22,1610612737,ATL,Atlanta Hawks,1610612744,GSW,Golden State Warriors,22101102,2022-03-25,121,110,1,231,11.0
4,2021-22,1610612737,ATL,Atlanta Hawks,1610612740,NOP,New Orleans Pelicans,22101064,2022-03-20,112,117,0,229,-5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3289,2023-24,1610612766,CHA,Charlotte Hornets,1610612748,MIA,Miami Heat,22300017,2023-11-14,105,111,0,216,-6.0
3290,2023-24,1610612766,CHA,Charlotte Hornets,1610612764,WAS,Washington Wizards,22300157,2023-11-08,116,132,0,248,-16.0
3291,2023-24,1610612766,CHA,Charlotte Hornets,1610612751,BKN,Brooklyn Nets,22300101,2023-10-30,121,133,0,254,-12.0
3292,2023-24,1610612766,CHA,Charlotte Hornets,1610612765,DET,Detroit Pistons,22300077,2023-10-27,99,111,0,210,-12.0
3293,2023-24,1610612766,CHA,Charlotte Hornets,1610612737,ATL,Atlanta Hawks,22300063,2023-10-25,116,110,1,226,6.0

In [20]:
df.

SyntaxError: invalid syntax (791285630.py, line 1)

## Feature Group Merging

In [54]:
from spam_data.feature_engineering.box_score_feature_group import *

In [55]:
rw = FixedRollingWindow()

Season 2021-22: 1230 games
Season 2022-23: 1230 games
Season 2023-24: 860 games
Season 2021-22: 1222 games
Season 2022-23: 1221 games
Season 2023-24: 851 games

C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\utility_functions.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])

In [56]:
rwdf = rw.process_data()

In [57]:
rwdf.dtypes

ROLL_HOME_PTS        float64
ROLL_HOME_FGM        float64
ROLL_HOME_FGA        float64
ROLL_HOME_FG_PCT     float64
ROLL_HOME_FG3M       float64
ROLL_HOME_FG3A       float64
ROLL_HOME_FG3_PCT    float64
ROLL_HOME_FTM        float64
ROLL_HOME_FTA        float64
ROLL_HOME_FT_PCT     float64
ROLL_HOME_OREB       float64
ROLL_HOME_DREB       float64
ROLL_HOME_REB        float64
ROLL_HOME_AST        float64
ROLL_HOME_STL        float64
ROLL_HOME_BLK        float64
ROLL_HOME_TOV        float64
ROLL_HOME_PF         float64
ROLL_AWAY_PTS        float64
ROLL_AWAY_FGM        float64
ROLL_AWAY_FGA        float64
ROLL_AWAY_FG_PCT     float64
ROLL_AWAY_FG3M       float64
ROLL_AWAY_FG3A       float64
ROLL_AWAY_FG3_PCT    float64
ROLL_AWAY_FTM        float64
ROLL_AWAY_FTA        float64
ROLL_AWAY_FT_PCT     float64
ROLL_AWAY_OREB       float64
ROLL_AWAY_DREB       float64
ROLL_AWAY_REB        float64
ROLL_AWAY_AST        float64
ROLL_AWAY_STL        float64
ROLL_AWAY_BLK        float64
ROLL_AWAY_TOV        float64
ROLL_AWAY_PF         float64
dtype: object

In [58]:
df.dtypes

SEASON_ID                         object
HOME_TEAM_ID                       int64
HOME_TEAM_ABBREVIATION            object
HOME_TEAM_NAME                    object
AWAY_TEAM_ID                       int64
AWAY_TEAM_ABBREVIATION            object
AWAY_TEAM_NAME                    object
GAME_ID                            int64
GAME_DATE                 datetime64[ns]
HOME_PTS                           int64
AWAY_PTS                           int64
GAME_RESULT                        int64
TOTAL_PTS                          int64
PLUS_MINUS                       float64
dtype: object

In [59]:
rwdf[rwdf["GAME_ID"] == 22300017]

KeyError: 'GAME_ID'

In [60]:
df.set_index("GAME_ID")

,SEASON_ID,HOME_TEAM_ID,HOME_TEAM_ABBREVIATION,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS
GAME_ID,,,,,,,,,,,,,
22101192,2021-22,1610612737,ATL,Atlanta Hawks,1610612764,WAS,Washington Wizards,2022-04-06,118,103,1,221,15.0
22101163,2021-22,1610612737,ATL,Atlanta Hawks,1610612751,BKN,Brooklyn Nets,2022-04-02,122,115,1,237,7.0
22100452,2021-22,1610612737,ATL,Atlanta Hawks,1610612739,CLE,Cleveland Cavaliers,2022-03-31,131,107,1,238,24.0
22101102,2021-22,1610612737,ATL,Atlanta Hawks,1610612744,GSW,Golden State Warriors,2022-03-25,121,110,1,231,11.0
22101064,2021-22,1610612737,ATL,Atlanta Hawks,1610612740,NOP,New Orleans Pelicans,2022-03-20,112,117,0,229,-5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22300017,2023-24,1610612766,CHA,Charlotte Hornets,1610612748,MIA,Miami Heat,2023-11-14,105,111,0,216,-6.0
22300157,2023-24,1610612766,CHA,Charlotte Hornets,1610612764,WAS,Washington Wizards,2023-11-08,116,132,0,248,-16.0
22300101,2023-24,1610612766,CHA,Charlotte Hornets,1610612751,BKN,Brooklyn Nets,2023-10-30,121,133,0,254,-12.0
22300077,2023-24,1610612766,CHA,Charlotte Hornets,1610612765,DET,Detroit Pistons,2023-10-27,99,111,0,210,-12.0
22300063,2023-24,1610612766,CHA,Charlotte Hornets,1610612737,ATL,Atlanta Hawks,2023-10-25,116,110,1,226,6.0

In [61]:
x = rw.merge_data_to_base(df)

In [62]:
x

,ROLL_HOME_PTS,ROLL_HOME_FGM,ROLL_HOME_FGA,ROLL_HOME_FG_PCT,ROLL_HOME_FG3M,ROLL_HOME_FG3A,ROLL_HOME_FG3_PCT,ROLL_HOME_FTM,ROLL_HOME_FTA,ROLL_HOME_FT_PCT,...,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS
GAME_ID,,,,,,,,,,,,,,,,,,,,,
22100001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Milwaukee Bucks,1610612751,BKN,Brooklyn Nets,2021-10-19,127,104,1,231,23.0
22100002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Los Angeles Lakers,1610612744,GSW,Golden State Warriors,2021-10-19,114,121,0,235,-7.0
22100004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Detroit Pistons,1610612741,CHI,Chicago Bulls,2021-10-20,88,94,0,182,-6.0
22100007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Memphis Grizzlies,1610612739,CLE,Cleveland Cavaliers,2021-10-20,132,121,1,253,11.0
22100012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Phoenix Suns,1610612743,DEN,Denver Nuggets,2021-10-20,98,110,0,208,-12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22300820,108.4,42.6,92.6,0.460,11.2,35.6,0.312,12.0,16.6,0.711,...,Washington Wizards,1610612739,CLE,Cleveland Cavaliers,2024-02-25,105,114,0,219,-9.0
22300829,125.0,48.2,87.8,0.548,12.8,31.6,0.405,15.8,20.2,0.781,...,Indiana Pacers,1610612761,TOR,Toronto Raptors,2024-02-26,122,130,0,252,-8.0
22300830,105.2,39.4,85.0,0.465,13.2,37.2,0.364,13.2,19.4,0.699,...,Memphis Grizzlies,1610612751,BKN,Brooklyn Nets,2024-02-26,86,111,0,197,-25.0
22300828,109.8,41.6,89.2,0.468,11.6,33.8,0.345,15.0,17.0,0.885,...,New York Knicks,1610612765,DET,Detroit Pistons,2024-02-26,113,111,1,224,2.0
22300831,125.0,47.0,90.6,0.520,14.4,37.2,0.391,16.6,22.6,0.747,...,Sacramento Kings,1610612748,MIA,Miami Heat,2024-02-26,110,121,0,231,-11.0

In [46]:
rw.df.join(df.set_index("GAME_ID"))

,GAME_ID,ROLL_HOME_PTS,ROLL_HOME_FGM,ROLL_HOME_FGA,ROLL_HOME_FG_PCT,ROLL_HOME_FG3M,ROLL_HOME_FG3A,ROLL_HOME_FG3_PCT,ROLL_HOME_FTM,ROLL_HOME_FTA,...,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS
525,22100001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
444,22100002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1180,22100004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1098,22100007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
812,22100012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3210,22300820,108.4,42.6,92.6,0.460,11.2,35.6,0.312,12.0,16.6,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2925,22300829,125.0,48.2,87.8,0.548,12.8,31.6,0.405,15.8,20.2,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
3181,22300830,105.2,39.4,85.0,0.465,13.2,37.2,0.364,13.2,19.4,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2871,22300828,109.8,41.6,89.2,0.468,11.6,33.8,0.345,15.0,17.0,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
3044,22300831,125.0,47.0,90.6,0.520,14.4,37.2,0.391,16.6,22.6,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN

In [47]:
df

,SEASON_ID,HOME_TEAM_ID,HOME_TEAM_ABBREVIATION,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_ID,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS
0,2021-22,1610612737,ATL,Atlanta Hawks,1610612764,WAS,Washington Wizards,22101192,2022-04-06,118,103,1,221,15.0
1,2021-22,1610612737,ATL,Atlanta Hawks,1610612751,BKN,Brooklyn Nets,22101163,2022-04-02,122,115,1,237,7.0
2,2021-22,1610612737,ATL,Atlanta Hawks,1610612739,CLE,Cleveland Cavaliers,22100452,2022-03-31,131,107,1,238,24.0
3,2021-22,1610612737,ATL,Atlanta Hawks,1610612744,GSW,Golden State Warriors,22101102,2022-03-25,121,110,1,231,11.0
4,2021-22,1610612737,ATL,Atlanta Hawks,1610612740,NOP,New Orleans Pelicans,22101064,2022-03-20,112,117,0,229,-5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3289,2023-24,1610612766,CHA,Charlotte Hornets,1610612748,MIA,Miami Heat,22300017,2023-11-14,105,111,0,216,-6.0
3290,2023-24,1610612766,CHA,Charlotte Hornets,1610612764,WAS,Washington Wizards,22300157,2023-11-08,116,132,0,248,-16.0
3291,2023-24,1610612766,CHA,Charlotte Hornets,1610612751,BKN,Brooklyn Nets,22300101,2023-10-30,121,133,0,254,-12.0
3292,2023-24,1610612766,CHA,Charlotte Hornets,1610612765,DET,Detroit Pistons,22300077,2023-10-27,99,111,0,210,-12.0
3293,2023-24,1610612766,CHA,Charlotte Hornets,1610612737,ATL,Atlanta Hawks,22300063,2023-10-25,116,110,1,226,6.0

In [48]:
rwdf

,GAME_ID,ROLL_HOME_PTS,ROLL_HOME_FGM,ROLL_HOME_FGA,ROLL_HOME_FG_PCT,ROLL_HOME_FG3M,ROLL_HOME_FG3A,ROLL_HOME_FG3_PCT,ROLL_HOME_FTM,ROLL_HOME_FTA,...,ROLL_AWAY_FTA,ROLL_AWAY_FT_PCT,ROLL_AWAY_OREB,ROLL_AWAY_DREB,ROLL_AWAY_REB,ROLL_AWAY_AST,ROLL_AWAY_STL,ROLL_AWAY_BLK,ROLL_AWAY_TOV,ROLL_AWAY_PF
525,22100001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
444,22100002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1180,22100004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1098,22100007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
812,22100012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3210,22300820,108.4,42.6,92.6,0.460,11.2,35.6,0.312,12.0,16.6,...,19.2,0.804,8.6,38.4,47.0,28.4,5.6,6.8,11.6,16.2
2925,22300829,125.0,48.2,87.8,0.548,12.8,31.6,0.405,15.8,20.2,...,17.6,0.812,9.4,32.8,42.2,29.8,5.8,5.2,12.6,16.6
3181,22300830,105.2,39.4,85.0,0.465,13.2,37.2,0.364,13.2,19.4,...,18.0,0.796,7.8,32.2,40.0,28.2,6.2,3.4,12.0,18.8
2871,22300828,109.8,41.6,89.2,0.468,11.6,33.8,0.345,15.0,17.0,...,19.0,0.722,13.8,34.4,48.2,27.2,7.6,4.0,14.8,23.8
3044,22300831,125.0,47.0,90.6,0.520,14.4,37.2,0.391,16.6,22.6,...,21.8,0.795,9.8,36.8,46.6,26.2,7.2,4.0,12.2,16.0

In [50]:
rwdf.set_index("GAME_ID").join(df.set_index("GAME_ID"))

,ROLL_HOME_PTS,ROLL_HOME_FGM,ROLL_HOME_FGA,ROLL_HOME_FG_PCT,ROLL_HOME_FG3M,ROLL_HOME_FG3A,ROLL_HOME_FG3_PCT,ROLL_HOME_FTM,ROLL_HOME_FTA,ROLL_HOME_FT_PCT,...,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS
GAME_ID,,,,,,,,,,,,,,,,,,,,,
22100001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Milwaukee Bucks,1610612751,BKN,Brooklyn Nets,2021-10-19,127,104,1,231,23.0
22100002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Los Angeles Lakers,1610612744,GSW,Golden State Warriors,2021-10-19,114,121,0,235,-7.0
22100004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Detroit Pistons,1610612741,CHI,Chicago Bulls,2021-10-20,88,94,0,182,-6.0
22100007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Memphis Grizzlies,1610612739,CLE,Cleveland Cavaliers,2021-10-20,132,121,1,253,11.0
22100012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Phoenix Suns,1610612743,DEN,Denver Nuggets,2021-10-20,98,110,0,208,-12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22300820,108.4,42.6,92.6,0.460,11.2,35.6,0.312,12.0,16.6,0.711,...,Washington Wizards,1610612739,CLE,Cleveland Cavaliers,2024-02-25,105,114,0,219,-9.0
22300829,125.0,48.2,87.8,0.548,12.8,31.6,0.405,15.8,20.2,0.781,...,Indiana Pacers,1610612761,TOR,Toronto Raptors,2024-02-26,122,130,0,252,-8.0
22300830,105.2,39.4,85.0,0.465,13.2,37.2,0.364,13.2,19.4,0.699,...,Memphis Grizzlies,1610612751,BKN,Brooklyn Nets,2024-02-26,86,111,0,197,-25.0
22300828,109.8,41.6,89.2,0.468,11.6,33.8,0.345,15.0,17.0,0.885,...,New York Knicks,1610612765,DET,Detroit Pistons,2024-02-26,113,111,1,224,2.0
22300831,125.0,47.0,90.6,0.520,14.4,37.2,0.391,16.6,22.6,0.747,...,Sacramento Kings,1610612748,MIA,Miami Heat,2024-02-26,110,121,0,231,-11.0

In [51]:
x

,GAME_ID,ROLL_HOME_PTS,ROLL_HOME_FGM,ROLL_HOME_FGA,ROLL_HOME_FG_PCT,ROLL_HOME_FG3M,ROLL_HOME_FG3A,ROLL_HOME_FG3_PCT,ROLL_HOME_FTM,ROLL_HOME_FTA,...,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS
525,22100001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
444,22100002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1180,22100004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1098,22100007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
812,22100012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3210,22300820,108.4,42.6,92.6,0.460,11.2,35.6,0.312,12.0,16.6,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2925,22300829,125.0,48.2,87.8,0.548,12.8,31.6,0.405,15.8,20.2,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
3181,22300830,105.2,39.4,85.0,0.465,13.2,37.2,0.364,13.2,19.4,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2871,22300828,109.8,41.6,89.2,0.468,11.6,33.8,0.345,15.0,17.0,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
3044,22300831,125.0,47.0,90.6,0.520,14.4,37.2,0.391,16.6,22.6,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN

In [ ]:
rwdf = rw.process_data(

In [ ]:
rwdf

In [ ]:
rwdf.columns

In [ ]:
df.columns

In [ ]:
df.head()

In [ ]:
rwdf.head()

## FE TOP

In [53]:
from spam_data.feature_engineering.box_score_ratios_feature_group import BoxScoreRatios
from spam_data.feature_engineering.box_score_feature_group import FixedRollingWindow

Season 2021-22: 1230 games
Season 2022-23: 1230 games
Season 2023-24: 860 games
Season 2021-22: 1222 games
Season 2022-23: 1221 games
Season 2023-24: 851 games

C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\utility_functions.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])

In [54]:
from spam_data.feature_engineering import build_dataset

In [55]:
df = build_dataset([BoxScoreRatios(), FixedRollingWindow()])

C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\utility_functions.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])
C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\utility_functions.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])

Season 2021-22: 1230 games
Season 2022-23: 1230 games
Season 2023-24: 860 games
Season 2021-22: 1222 games
Season 2022-23: 1221 games
Season 2023-24: 851 games
Season 2021-22: 1230 games
Season 2022-23: 1230 games
Season 2023-24: 860 games
Season 2021-22: 1222 games
Season 2022-23: 1221 games
Season 2023-24: 851 games
          ROLL_HOME_PTS  ROLL_HOME_FGM  ROLL_HOME_FGA  ROLL_HOME_FG_PCT  \
GAME_ID
22100032          123.0           49.0           98.0             0.500
22100033          121.0           45.0           93.0             0.484
22100029           83.0           30.0           97.0             0.309
22100031          124.0           42.0           87.0             0.483
22100037          124.0           48.0           95.0             0.505

          ROLL_HOME_FG3M  ROLL_HOME_FG3A  ROLL_HOME_FG3_PCT  ROLL_HOME_FTM  \
GAME_ID
22100032            13.0            30.0              0.433           12.0
22100033            12.0            35.0              0.343           19.0
22100029             7.0            34.0              0.206           16.0
22100031            16.0            38.0              0.421           24.0
22100037            17.0            38.0              0.447           11.0

          ROLL_HOME_FTA  ROLL_HOME_FT_PCT  ...  ROLL_AWAY_FTA  \
GAME_ID                                    ...
22100032           18.0             0.667  ...           29.0
22100033           22.0             0.864  ...           28.0
22100029           22.0             0.727  ...           13.0
22100031           31.0             0.774  ...           16.0
22100037           14.0             0.786  ...           23.0

          ROLL_AWAY_FT_PCT  ROLL_AWAY_OREB  ROLL_AWAY_DREB  ROLL_AWAY_REB  \
GAME_ID
22100032             0.655             5.0            33.0           38.0
22100033             0.750             7.0            40.0           47.0
22100029             0.923            10.0            40.0           50.0
22100031             0.813             9.0            33.0           42.0
22100037             0.739            15.0            41.0           56.0

          ROLL_AWAY_AST  ROLL_AWAY_STL  ROLL_AWAY_BLK  ROLL_AWAY_TOV  \
GAME_ID
22100032           19.0            6.0            0.0           15.0
22100033           31.0            8.0            2.0           11.0
22100029           16.0            7.0            3.0           15.0
22100031           26.0            7.0            5.0           16.0
22100037           34.0           13.0            9.0           18.0

          ROLL_AWAY_PF
GAME_ID
22100032          26.0
22100033          22.0
22100029          21.0
22100031          20.0
22100037          24.0

[5 rows x 36 columns]
          ROLL_HOME_PTS  ROLL_HOME_FGM  ROLL_HOME_FGA  ROLL_HOME_FG_PCT  \
GAME_ID
22100032          123.0           49.0           98.0             0.500
22100033          121.0           45.0           93.0             0.484
22100029           83.0           30.0           97.0             0.309
22100031          124.0           42.0           87.0             0.483
22100037          124.0           48.0           95.0             0.505

          ROLL_HOME_FG3M  ROLL_HOME_FG3A  ROLL_HOME_FG3_PCT  ROLL_HOME_FTM  \
GAME_ID
22100032            13.0            30.0              0.433           12.0
22100033            12.0            35.0              0.343           19.0
22100029             7.0            34.0              0.206           16.0
22100031            16.0            38.0              0.421           24.0
22100037            17.0            38.0              0.447           11.0

          ROLL_HOME_FTA  ROLL_HOME_FT_PCT  ...  ROLL_AWAY_STL  ROLL_AWAY_BLK  \
GAME_ID                                    ...
22100032           18.0             0.667  ...            6.0            0.0
22100033           22.0             0.864  ...            8.0            2.0
22100029           22.0             0.727  ...            7.0            3.0
22100031           31.0             0.774  ...            7.0            5.0
22100037           14.0             0.786  ...           13.0            9.0

          ROLL_AWAY_TOV  ROLL_AWAY_PF  ROLL_HOME_3A_RATE  \
GAME_ID
22100032           15.0          26.0           0.306122
22100033           11.0          22.0           0.376344
22100029           15.0          21.0           0.350515
22100031           16.0          20.0           0.436782
22100037           18.0          24.0           0.400000

          ROLL_HOME_ASSIST_TO_TURNOVER_RATE  ROLL_HOME_OTOD_REBRATE  \
GAME_ID
22100032                           4.000000                0.433333
22100033                           2.083333                0.225000
22100029                           0.736842                0.542857
22100031                           1.444444                0.393939
22100037                           1.705882                0.227273

          ROLL_AWAY_3A_RATE  ROLL_AWAY_ASSIST_TO_TURNOVER_RATE  \
GAME_ID
22100032           0.500000                           1.266667
22100033           0.372093                           2.818182
22100029           0.462366                           1.066667
22100031           0.333333                           1.625000
22100037           0.487179                           1.888889

          ROLL_AWAY_OTOD_REBRATE
GAME_ID
22100032                0.151515
22100033                0.175000
22100029                0.250000
22100031                0.272727
22100037                0.365854

[5 rows x 42 columns]
Index(['ROLL_HOME_PTS', 'ROLL_HOME_FGM', 'ROLL_HOME_FGA', 'ROLL_HOME_FG_PCT',
       'ROLL_HOME_FG3M', 'ROLL_HOME_FG3A', 'ROLL_HOME_FG3_PCT',
       'ROLL_HOME_FTM', 'ROLL_HOME_FTA', 'ROLL_HOME_FT_PCT', 'ROLL_HOME_OREB',
       'ROLL_HOME_DREB', 'ROLL_HOME_REB', 'ROLL_HOME_AST', 'ROLL_HOME_STL',
       'ROLL_HOME_BLK', 'ROLL_HOME_TOV', 'ROLL_HOME_PF', 'ROLL_AWAY_PTS',
       'ROLL_AWAY_FGM', 'ROLL_AWAY_FGA', 'ROLL_AWAY_FG_PCT', 'ROLL_AWAY_FG3M',
       'ROLL_AWAY_FG3A', 'ROLL_AWAY_FG3_PCT', 'ROLL_AWAY_FTM', 'ROLL_AWAY_FTA',
       'ROLL_AWAY_FT_PCT', 'ROLL_AWAY_OREB', 'ROLL_AWAY_DREB', 'ROLL_AWAY_REB',
       'ROLL_AWAY_AST', 'ROLL_AWAY_STL', 'ROLL_AWAY_BLK', 'ROLL_AWAY_TOV',
       'ROLL_AWAY_PF', 'ROLL_HOME_3A_RATE',
       'ROLL_HOME_ASSIST_TO_TURNOVER_RATE', 'ROLL_HOME_OTOD_REBRATE',
       'ROLL_AWAY_3A_RATE', 'ROLL_AWAY_ASSIST_TO_TURNOVER_RATE',
       'ROLL_AWAY_OTOD_REBRATE'],
      dtype='object')

C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\box_score_ratios_feature_group.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cur] = df[f"{pref}FG3A"] / df[f"{pref}FGA"]
C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\box_score_ratios_feature_group.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cur] = df[f"{pref}AST"] / df[f"{pref}TOV"]
C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\box_score_ratios_feature_group.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cur] = df[f"{pref}OREB"] / df[f"{pref}DREB"]
C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\box_score_ratios_feature_group.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cur] = df[f"{pref}FG3A"] / df[f"{pref}FGA"]
C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\box_score_ratios_feature_group.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cur] = df[f"{pref}AST"] / df[f"{pref}TOV"]
C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\box_score_ratios_feature_group.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cur] = df[f"{pref}OREB"] / df[f"{pref}DREB"]

In [56]:
df.head()

,GAME_ID,ROLL_HOME_PTS,ROLL_HOME_FGM,ROLL_HOME_FGA,ROLL_HOME_FG_PCT,ROLL_HOME_FG3M,ROLL_HOME_FG3A,ROLL_HOME_FG3_PCT,ROLL_HOME_FTM,ROLL_HOME_FTA,...,HOME_TEAM_NAME,AWAY_TEAM_ID,AWAY_TEAM_ABBREVIATION,AWAY_TEAM_NAME,GAME_DATE,HOME_PTS,AWAY_PTS,GAME_RESULT,TOTAL_PTS,PLUS_MINUS
26,22100032,123.0,49.0,98.0,0.500,13.0,30.0,0.433,12.0,18.0,...,San Antonio Spurs,1.610613e+09,MIL,Milwaukee Bucks,2021-10-23,111.0,121.0,0.0,232.0,-10.0
27,22100033,121.0,45.0,93.0,0.484,12.0,35.0,0.343,19.0,22.0,...,Portland Trail Blazers,1.610613e+09,PHX,Phoenix Suns,2021-10-23,134.0,105.0,1.0,239.0,29.0
29,22100029,83.0,30.0,97.0,0.309,7.0,34.0,0.206,16.0,22.0,...,Toronto Raptors,1.610613e+09,DAL,Dallas Mavericks,2021-10-23,95.0,103.0,0.0,198.0,-8.0
32,22100031,124.0,42.0,87.0,0.483,16.0,38.0,0.421,24.0,31.0,...,Minnesota Timberwolves,1.610613e+09,NOP,New Orleans Pelicans,2021-10-23,96.0,89.0,1.0,185.0,7.0
35,22100037,124.0,48.0,95.0,0.505,17.0,38.0,0.447,11.0,14.0,...,Houston Rockets,1.610613e+09,BOS,Boston Celtics,2021-10-24,97.0,107.0,0.0,204.0,-10.0

In [58]:
df.columns

Index(['GAME_ID', 'ROLL_HOME_PTS', 'ROLL_HOME_FGM', 'ROLL_HOME_FGA',
       'ROLL_HOME_FG_PCT', 'ROLL_HOME_FG3M', 'ROLL_HOME_FG3A',
       'ROLL_HOME_FG3_PCT', 'ROLL_HOME_FTM', 'ROLL_HOME_FTA',
       'ROLL_HOME_FT_PCT', 'ROLL_HOME_OREB', 'ROLL_HOME_DREB', 'ROLL_HOME_REB',
       'ROLL_HOME_AST', 'ROLL_HOME_STL', 'ROLL_HOME_BLK', 'ROLL_HOME_TOV',
       'ROLL_HOME_PF', 'ROLL_AWAY_PTS', 'ROLL_AWAY_FGM', 'ROLL_AWAY_FGA',
       'ROLL_AWAY_FG_PCT', 'ROLL_AWAY_FG3M', 'ROLL_AWAY_FG3A',
       'ROLL_AWAY_FG3_PCT', 'ROLL_AWAY_FTM', 'ROLL_AWAY_FTA',
       'ROLL_AWAY_FT_PCT', 'ROLL_AWAY_OREB', 'ROLL_AWAY_DREB', 'ROLL_AWAY_REB',
       'ROLL_AWAY_AST', 'ROLL_AWAY_STL', 'ROLL_AWAY_BLK', 'ROLL_AWAY_TOV',
       'ROLL_AWAY_PF', 'ROLL_HOME_3A_RATE',
       'ROLL_HOME_ASSIST_TO_TURNOVER_RATE', 'ROLL_HOME_OTOD_REBRATE',
       'ROLL_AWAY_3A_RATE', 'ROLL_AWAY_ASSIST_TO_TURNOVER_RATE',
       'ROLL_AWAY_OTOD_REBRATE', 'index', 'SEASON_ID', 'HOME_TEAM_ID',
       'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_NAME', 'AWAY_TEAM_ID',
       'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_NAME', 'GAME_DATE', 'HOME_PTS',
       'AWAY_PTS', 'GAME_RESULT', 'TOTAL_PTS', 'PLUS_MINUS'],
      dtype='object')

In [43]:
fe = BoxScoreRatios()

In [44]:
fe.process_data()

          ROLL_HOME_PTS  ROLL_HOME_FGM  ROLL_HOME_FGA  ROLL_HOME_FG_PCT  \
GAME_ID
22100032          123.0           49.0           98.0             0.500
22100033          121.0           45.0           93.0             0.484
22100029           83.0           30.0           97.0             0.309
22100031          124.0           42.0           87.0             0.483
22100037          124.0           48.0           95.0             0.505

          ROLL_HOME_FG3M  ROLL_HOME_FG3A  ROLL_HOME_FG3_PCT  ROLL_HOME_FTM  \
GAME_ID
22100032            13.0            30.0              0.433           12.0
22100033            12.0            35.0              0.343           19.0
22100029             7.0            34.0              0.206           16.0
22100031            16.0            38.0              0.421           24.0
22100037            17.0            38.0              0.447           11.0

          ROLL_HOME_FTA  ROLL_HOME_FT_PCT  ...  ROLL_AWAY_FTA  \
GAME_ID                                    ...
22100032           18.0             0.667  ...           29.0
22100033           22.0             0.864  ...           28.0
22100029           22.0             0.727  ...           13.0
22100031           31.0             0.774  ...           16.0
22100037           14.0             0.786  ...           23.0

          ROLL_AWAY_FT_PCT  ROLL_AWAY_OREB  ROLL_AWAY_DREB  ROLL_AWAY_REB  \
GAME_ID
22100032             0.655             5.0            33.0           38.0
22100033             0.750             7.0            40.0           47.0
22100029             0.923            10.0            40.0           50.0
22100031             0.813             9.0            33.0           42.0
22100037             0.739            15.0            41.0           56.0

          ROLL_AWAY_AST  ROLL_AWAY_STL  ROLL_AWAY_BLK  ROLL_AWAY_TOV  \
GAME_ID
22100032           19.0            6.0            0.0           15.0
22100033           31.0            8.0            2.0           11.0
22100029           16.0            7.0            3.0           15.0
22100031           26.0            7.0            5.0           16.0
22100037           34.0           13.0            9.0           18.0

          ROLL_AWAY_PF
GAME_ID
22100032          26.0
22100033          22.0
22100029          21.0
22100031          20.0
22100037          24.0

[5 rows x 36 columns]
          ROLL_HOME_PTS  ROLL_HOME_FGM  ROLL_HOME_FGA  ROLL_HOME_FG_PCT  \
GAME_ID
22100032          123.0           49.0           98.0             0.500
22100033          121.0           45.0           93.0             0.484
22100029           83.0           30.0           97.0             0.309
22100031          124.0           42.0           87.0             0.483
22100037          124.0           48.0           95.0             0.505

          ROLL_HOME_FG3M  ROLL_HOME_FG3A  ROLL_HOME_FG3_PCT  ROLL_HOME_FTM  \
GAME_ID
22100032            13.0            30.0              0.433           12.0
22100033            12.0            35.0              0.343           19.0
22100029             7.0            34.0              0.206           16.0
22100031            16.0            38.0              0.421           24.0
22100037            17.0            38.0              0.447           11.0

          ROLL_HOME_FTA  ROLL_HOME_FT_PCT  ...  ROLL_AWAY_STL  ROLL_AWAY_BLK  \
GAME_ID                                    ...
22100032           18.0             0.667  ...            6.0            0.0
22100033           22.0             0.864  ...            8.0            2.0
22100029           22.0             0.727  ...            7.0            3.0
22100031           31.0             0.774  ...            7.0            5.0
22100037           14.0             0.786  ...           13.0            9.0

          ROLL_AWAY_TOV  ROLL_AWAY_PF  ROLL_HOME_3A_RATE  \
GAME_ID
22100032           15.0          26.0           0.306122
22100033           11.0          22.0           0.376344
22100029           15.0          21.0           0.350515
22100031           16.0          20.0           0.436782
22100037           18.0          24.0           0.400000

          ROLL_HOME_ASSIST_TO_TURNOVER_RATE  ROLL_HOME_OTOD_REBRATE  \
GAME_ID
22100032                           4.000000                0.433333
22100033                           2.083333                0.225000
22100029                           0.736842                0.542857
22100031                           1.444444                0.393939
22100037                           1.705882                0.227273

          ROLL_AWAY_3A_RATE  ROLL_AWAY_ASSIST_TO_TURNOVER_RATE  \
GAME_ID
22100032           0.500000                           1.266667
22100033           0.372093                           2.818182
22100029           0.462366                           1.066667
22100031           0.333333                           1.625000
22100037           0.487179                           1.888889

          ROLL_AWAY_OTOD_REBRATE
GAME_ID
22100032                0.151515
22100033                0.175000
22100029                0.250000
22100031                0.272727
22100037                0.365854

[5 rows x 42 columns]
Index(['ROLL_HOME_PTS', 'ROLL_HOME_FGM', 'ROLL_HOME_FGA', 'ROLL_HOME_FG_PCT',
       'ROLL_HOME_FG3M', 'ROLL_HOME_FG3A', 'ROLL_HOME_FG3_PCT',
       'ROLL_HOME_FTM', 'ROLL_HOME_FTA', 'ROLL_HOME_FT_PCT', 'ROLL_HOME_OREB',
       'ROLL_HOME_DREB', 'ROLL_HOME_REB', 'ROLL_HOME_AST', 'ROLL_HOME_STL',
       'ROLL_HOME_BLK', 'ROLL_HOME_TOV', 'ROLL_HOME_PF', 'ROLL_AWAY_PTS',
       'ROLL_AWAY_FGM', 'ROLL_AWAY_FGA', 'ROLL_AWAY_FG_PCT', 'ROLL_AWAY_FG3M',
       'ROLL_AWAY_FG3A', 'ROLL_AWAY_FG3_PCT', 'ROLL_AWAY_FTM', 'ROLL_AWAY_FTA',
       'ROLL_AWAY_FT_PCT', 'ROLL_AWAY_OREB', 'ROLL_AWAY_DREB', 'ROLL_AWAY_REB',
       'ROLL_AWAY_AST', 'ROLL_AWAY_STL', 'ROLL_AWAY_BLK', 'ROLL_AWAY_TOV',
       'ROLL_AWAY_PF', 'ROLL_HOME_3A_RATE',
       'ROLL_HOME_ASSIST_TO_TURNOVER_RATE', 'ROLL_HOME_OTOD_REBRATE',
       'ROLL_AWAY_3A_RATE', 'ROLL_AWAY_ASSIST_TO_TURNOVER_RATE',
       'ROLL_AWAY_OTOD_REBRATE'],
      dtype='object')

C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\box_score_ratios_feature_group.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cur] = df[f"{pref}FG3A"] / df[f"{pref}FGA"]
C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\box_score_ratios_feature_group.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cur] = df[f"{pref}AST"] / df[f"{pref}TOV"]
C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\box_score_ratios_feature_group.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cur] = df[f"{pref}OREB"] / df[f"{pref}DREB"]
C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\box_score_ratios_feature_group.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cur] = df[f"{pref}FG3A"] / df[f"{pref}FGA"]
C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\box_score_ratios_feature_group.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cur] = df[f"{pref}AST"] / df[f"{pref}TOV"]
C:\Users\james\Documents\Capstone\sports_betting\james\spam_data\spam_data\feature_engineering\box_score_ratios_feature_group.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cur] = df[f"{pref}OREB"] / df[f"{pref}DREB"]

,ROLL_HOME_3A_RATE,ROLL_HOME_ASSIST_TO_TURNOVER_RATE,ROLL_HOME_OTOD_REBRATE,ROLL_AWAY_3A_RATE,ROLL_AWAY_ASSIST_TO_TURNOVER_RATE,ROLL_AWAY_OTOD_REBRATE
GAME_ID,,,,,,
22100032,0.306122,4.000000,0.433333,0.500000,1.266667,0.151515
22100033,0.376344,2.083333,0.225000,0.372093,2.818182,0.175000
22100029,0.350515,0.736842,0.542857,0.462366,1.066667,0.250000
22100031,0.436782,1.444444,0.393939,0.333333,1.625000,0.272727
22100037,0.400000,1.705882,0.227273,0.487179,1.888889,0.365854
...,...,...,...,...,...,...
22300820,0.384449,1.942029,0.314465,0.421053,2.448276,0.223958
22300829,0.359909,2.232877,0.221477,0.372549,2.365079,0.286585
22300830,0.437647,2.107692,0.262821,0.464853,2.350000,0.242236
22300828,0.378924,2.132075,0.413793,0.309572,1.837838,0.401163
22300831,0.410596,2.877551,0.211765,0.397229,2.147541,0.266304

In [10]:
df

NameError: name 'df' is not defined