In [7]:
%load_ext autoreload
%autoreload 2

In [1]:
import spam_data

In [3]:
from spam_data.api.game_stats import *

In [8]:
from spam_data.api.team_stats import *

In [4]:
df = get_games()

In [9]:
team = get_teams()

In [10]:
team

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976
23,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974
26,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988

In [6]:
df

,SEASON_ID_AWAY,TEAM_ID_AWAY,TEAM_ABBREVIATION_AWAY,TEAM_NAME_AWAY,GAME_ID,GAME_DATE_AWAY,MATCHUP_AWAY,WL_AWAY,MIN_AWAY,FGM_AWAY,...,DREB_HOME,REB_HOME,AST_HOME,STL_HOME,BLK_HOME,TOV_HOME,PF_HOME,PTS_HOME,PLUS_MINUS_HOME,VIDEO_AVAILABLE_HOME
1,22023,1610612756,PHX,Phoenix Suns,0022300062,2023-10-24,PHX @ GSW,W,240,42,...,31,49,19,11,6,11,23,104,-4,1
3,22023,1610612747,LAL,Los Angeles Lakers,0022300061,2023-10-24,LAL @ DEN,L,240,41,...,33,42,29,9,6,12,15,119,12,1
6,22023,1610612750,MIN,Minnesota Timberwolves,0022300069,2023-10-25,MIN @ TOR,L,240,34,...,39,47,27,9,11,14,18,97,3,1
9,22023,1610612739,CLE,Cleveland Cavaliers,0022300067,2023-10-25,CLE @ BKN,W,240,44,...,37,50,30,6,6,18,16,113,-1,1
10,22023,1610612765,DET,Detroit Pistons,0022300068,2023-10-25,DET @ MIA,L,240,41,...,32,48,22,11,3,7,18,103,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1680,22023,1610612766,CHA,Charlotte Hornets,0022300811,2024-02-23,CHA @ GSW,L,240,32,...,40,53,28,7,7,22,15,97,13,1
1682,22023,1610612759,SAS,San Antonio Spurs,0022300813,2024-02-23,SAS @ LAL,L,240,42,...,36,46,28,7,4,13,18,123,5,1
1684,22023,1610612751,BKN,Brooklyn Nets,0022300815,2024-02-24,BKN @ MIN,None,0,10,...,9,9,5,0,1,4,2,17,-5,0
1687,22023,1610612738,BOS,Boston Celtics,0022300816,2024-02-24,BOS @ NYK,None,60,24,...,10,15,10,1,1,6,7,54,-4,0
1688,22023,1610612753,ORL,Orlando Magic,0022300814,2024-02-24,ORL @ DET,None,120,30,...,20,24,20,5,4,6,13,76,1,0